### ISSUE TITLE
XGROUP doc isn't clear that only a single sub-command allowed

### ISSUE THREAD

**Issue by gkorland** [redis/redis-doc#1021]
```
XGROUP [CREATE key groupname id-or-$] [SETID key id-or-$] [DESTROY key groupname] [DELCONSUMER key groupname consumername]
```

Should be:

```
XGROUP [CREATE key groupname id-or-$]/[SETID key id-or-$]/[DESTROY key groupname]/[DELCONSUMER key groupname consumername]
```
Or maybe it's better for clreaty to break it into 4 "commands" cause both ways indicate that all of the options are optional --> "XGROUP" with no arguments is a valid command

``` 
XGROUP CREATE key groupname id|$
XGROUP SETID key id|$ 
XGROUP DESTROY key groupname
XGROUP DELCONSUMER key groupname consumername
XGROUP HELP
```

**Comment by itamarhaber** [comment]
Breaking makes sense - it is already the case with some of the subcommanded commands.

**Comment by gkorland** [comment]
```
XINFO [CONSUMERS key groupname] [GROUPS key] [STREAM key] [HELP]
```
Seems to have a similar issue

**Comment by mich-elle-luna** [comment]
XGROUP and XINFO command documentation has been broken into separate docs as suggested above, https://redis.io/commands/xgroup-create/ https://redis.io/commands/xgroup-setid/ and so on, closing as complete.
