### ISSUE TITLE
Undocumented command CREATE

### ISSUE THREAD

**Issue by nolimitdev** [redis/redis-doc#1038]
As recommended in https://github.com/antirez/redis/issues/5564 I report doc related issue here.

Cluster tutorial (https://redis.io/topics/cluster-tutorial) says that since Redis 5 we can start cluster with command `redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 --cluster-replicas 1` 

> The command used here is **create**, since we want to create a new cluster. The option --cluster-replicas 1 means that we want a slave for every master created. The other arguments are the list of addresses of the instances I want to use to create the new cluster.

I can not find where is "create" command documented. It is missing in list of commands (see https://redis.io/commands) and also redis-cli page does not mention cluster at all (see https://redis.io/topics/rediscli). Also flags `--cluster` and `--cluster-replicas` should be documented.

**Comment by AngusP** [comment]
So the `create` here is not a Redis command (so shouldn't be in https://redis.io/commands) and is instead part of the new Cluster Management tools that are built in to `redis-cli` (they used to be in `redis-trib.rb`.) Understandably this might be a little confusing as without the `--cluster` flag it would have been passed straight through to Redis.

You can see the docs for these tools here https://redis.io/topics/cluster-tutorial

**Comment by zuiderkwast** [comment]
Also try `redis-cli --help`

**Comment by nermiller** [comment]
Closing as resolved
