### ISSUE TITLE
Sampling behavior of SPOP and SRANDMEMBER

### ISSUE THREAD

**Issue by gimmeao** [redis/redis-doc#1084]
The section where it discusses sampling behavior could be improved as I describe here: http://theshfl.com/redis_sets. I think the easiest way to fix it would be to say that in practical terms, for sets of a few hundred up to 10k (and I didn't look at set sizes larger than this) it looks like about a third of the IDs are sampled about half as often as the next third, and that third is in turn sampled about half as often as the last third. This would be an easy way for a developer to visualize whether or not the methods would work for their use case.

**Comment by mich-elle-luna** [comment]
As mentioned at the end of your article, this has likely changed/been updated, closing.
