### ISSUE TITLE
inputed text in example is not aligned

### ISSUE THREAD

**Issue by ZhangChaoWN** [redis/redis-doc#1298]
screen shot:
<img width="476" alt="Screen Shot 2020-05-06 at 5 42 55 PM" src="https://user-images.githubusercontent.com/9245192/81167791-6b05e100-8fc8-11ea-8928-593120464d1b.png">

**Comment by itamarhaber** [comment]
Hello @ZhangChaoWN 

Thanks for reporting this glitch. Is it happening on a specific page? Can you share more details about your browser/os?

**Comment by ZhangChaoWN** [comment]
> Hello @ZhangChaoWN
> 
> Thanks for reporting this glitch. Is it happening on a specific page? Can you share more details about your browser/os?

I tried different on browsers(chrome, firefox, safari) on my device, the glitch exists all time. I also tried different page(https://redis.io/commands/get, https://redis.io/commands/incr, and https://redis.io/commands/expire), it exists all time still
OS: macOS 10.15.4
device: MacBook Pro (Retina, 13-inch, Mid 2014)

**Comment by qichengzx** [comment]
The input form should add the style "float:left".

**Comment by itamarhaber** [comment]
Thanks for the fix suggestion @qichengzx - implemented in ac4ead0.

@ZhangChaoWN - please verify this resolves the issue and close.

**Comment by ZhangChaoWN** [comment]
look good to me
