### ISSUE TITLE
use tonumber is not required in rate limiter lua script

### ISSUE THREAD

**Issue by ZhangChaoWN** [redis/redis-doc#1300]
in [https://redis.io/commands/incr](), the lua code:
```lua
local current
current = redis.call("incr",KEYS[1])
if tonumber(current) == 1 then
    redis.call("expire",KEYS[1],1)
end
```
date type of `current` should already be number, because redis convert interger to lua number automatically, so use of tonumber is not required

**Comment by ayruslore** [comment]
Added a commit fixing the issue and opened a new pull request - https://github.com/redis/redis-doc/pull/1496
