### ISSUE TITLE
XADD documentation doesn't specifically outline what is returned when the operation fails

### ISSUE THREAD

**Issue by alexkhorton** [redis/redis-doc#1332]
The XADD documentation (https://redis.io/commands/xadd) does not specifically state what is returned by a failed XADD.

Between this statement:
When a user specified an explicit ID to XADD, the minimum valid ID is 0-1, and the user must specify an ID which is greater than any other ID currently inside the stream, otherwise the command will fail.

And this statement:
The command returns the ID of the added entry.

It isn't clear what happens when the XADD fails and no entry is added.

Could you please update the document to specifically state whether what is returned on failure? I assume it's either (1) the ID provided to the XADD command or (2) some token indicating failure.

Thanks!

**Comment by zuiderkwast** [comment]
Fixed by #1495
