### ISSUE TITLE
Question about write-permission

### ISSUE THREAD

**Issue by charsyam** [redis/redis-doc#1342]
Hi, @oranagra and @itamarhaber 

after changing github from antirez/redis-doc to redis/redis-doc

I lost my write-permission to merge redis-doc.

Is there any rule change? or Could you give me a write permission for this project again?

**Comment by itamarhaber** [comment]
Hello dear @charsyam 

The change was unintentional and probably my mistake while we were moving things around :) Do you want to continue helping in this repo?

**Comment by mich-elle-luna** [comment]
Contributor question, not a doc issue.
