### ISSUE TITLE
May I make a pull request for my Binary-Indexed-Tree (Fenwick Tree) module?

### ISSUE THREAD

**Issue by fzyzcjy** [redis/redis-doc#1351]
Hi thanks for the wonderful redis! I have implemented a binary indexed tree data structure. Seeing the [official doc](https://redis.io/modules) said that we can make PR about our modules, I wonder whether my module is interesting? If so, I will make my code more neat and open source it :)

**Comment by itamarhaber** [comment]
Hello @fzyzcjy 

Feel free to make any relevant PRs to the docs. Specifically, any OSS Redis module deserves a place here :)

**Comment by fzyzcjy** [comment]
Thanks! I will do that in my free time.
