### ISSUE TITLE
SET: KEEPTTL is exclusive with EX and PX

### ISSUE THREAD

**Issue by bmerry** [redis/redis-doc#1368]
The signature for SET is documented as
```
 SET key value [EX seconds|PX milliseconds] [NX|XX] [KEEPTTL] 
```

However, KEEPTTL cannot be used together with EX or PX, so it should be
```
 SET key value [EX seconds|PX milliseconds|KEEPTTL] [NX|XX]
```

**Comment by itamarhaber** [comment]
Hello @bmerry - that's a valid observation, thanks. Would you like to open a PR to address it? (hint: edit the file commands.json for the desired effect)

**Comment by bmerry** [comment]
I'll take a look when I get a chance.

**Comment by itamarhaber** [comment]
Thanks - I took care of it :)
