### ISSUE TITLE
ASKING is not documented

### ISSUE THREAD

**Issue by hubo1016** [redis/redis-doc#1369]
http://redis.io/topics/cluster-spec says that there should be an "asking" command when client is redirected by -ASK. But the command does not appear in commands document. Neither do the reference implementation implements the command.
1. Is the command still not implemented?
2. If the command is designed, what is the scope of "ASKING"? When will the asking status be cleared? Should there be a "NOTASKING" command?

**Comment by mich-elle-luna** [comment]
https://redis.io/commands/asking/
