### ISSUE TITLE
Documentation and/or enhancement request: Add to ACL documentation examples for replication and sentinel user

### ISSUE THREAD

**Issue by nickwilliams-eventbrite** [redis/redis-doc#1377]
With ACLs in Redis 6, a Redis admin can create different users for different tasks and assign them different "permissions." This could include having a user for replicas to use when replicating off the master and/or having a user for sentinels to use when monitoring the master.

However, the documentation for ACLs (https://redis.io/topics/acl) does not include examples for replication and sentinel users, so one has to experiment incrementally adding command permissions to the ACLs to figure out which commands to specify to provide the minimum-necessary permissions for replication and sentinel users.

Given this, I make the following either/and recommendations:

- Update the ACL documentation to include an example for the minimum-necessary ACL for a replica user and an example for the minimum-necessary ACL for a sentinel user.
- Even better, add `replication` and `sentinel` command categories that include the minimum-necessary permissions for those respective tasks, so that ACLs can be specified with something like `user replica_user +@replication ...` and `user sentinel_user +@sentinel`.

**Comment by wKavey** [comment]
d

**Comment by wKavey** [comment]
Along the same vein, it would be nice to document what the required arguments are for `masterauth` (replication) and `sentinel auth-pass` (sentinel) when using ACLs on a master. I'm trying to implement support for ACLs in https://github.com/aio-libs/aioredis and currently there seems to be no guidance on this matter.

**Comment by mich-elle-luna** [comment]
the https://redis.io/docs/management/security/acl/ topic now include a section for sentinel and replica user permissions and examples.

**Comment by dylannorthrup** [comment]
For anyone happening on this like I did, the current link to ACL docs (as of 30 Sept 2025) is https://redis.io/docs/latest/operate/oss_and_stack/management/security/acl/
