### ISSUE TITLE
https://redis.io/topics/acl page format error

### ISSUE THREAD

**Issue by tomatostranger** [redis/redis-doc#1387]
![format erro](https://user-images.githubusercontent.com/12868350/92864597-e02e6a80-f42f-11ea-8051-a0b594d11d35.png)

"Allow and disallow certain keys" section would be better if it formats like below, since multiple Asterisks are in the context.

* `~<pattern>`: Add a pattern of keys that can be mentioned as part of commands. For instance `~*` allows all the keys. The pattern is a glob-style pattern like the one of KEYS.  It is possible to specify multiple patterns.

* `allkeys`: Alias for `~*`.
* `resetkeys`: Flush the list of allowed keys patterns. For instance the ACL `~foo:* ~bar:* resetkeys ~objects:*`, will result in the client only be able to access keys matching the pattern `objects:*`.

**Comment by itamarhaber** [comment]
Thanks for reporting this @tomatostranger 🍅 should be fixed now.
