### ISSUE TITLE
LPOS behaviour when maxlen is set to 0 is not documented

### ISSUE THREAD

**Issue by Yanisky** [redis/redis-doc#1429]
I'm new to redis but I've noticed that in LPOS having a `maxlen`  of 0 is the same as not having `maxlen` but this behaviour is not documented.

The reason I didn't open a pull request for this is because I'm unsure if this is a bug or intended behaviour.

**Comment by itamarhaber** [comment]
Hi @Yanisky 

Welcome to Redis, and I hope you're enjoying the experience :)

Thanks for bringing this up - this indeed would benefit from clarification. As you've noticed, `MAXLEN 0` is the default and results in unlimited comparisons (i.e., the entire list). Please feel free to open a PR that resolves this issue.

**Comment by Yanisky** [comment]
Thank you for the warm welcome @itamarhaber . 

It's an awesome database! 

Would it be a good idea to add a test for maxlen 0? As you can see [here](https://github.com/redis/redis/blob/c3f9e017946cffdc3e7166e96e9ff98484db7963/tests/unit/type/list.tcl#L53-L59), no test exists for maxlen 0
