### ISSUE TITLE
LMOVE doc examples were likely run with Redis version < 6.2.0 - "ERR Unknown or disabled command 'LMOVE'"

### ISSUE THREAD

**Issue by ztaylor54** [redis/redis-doc#1462]
https://github.com/redis/redis-doc/blob/master/commands/lmove.md

See the examples [here](https://redis.io/commands/lmove), with screenshot for ease (and posterity):

![Screen Shot 2020-12-10 at 11 33 46 AM](https://user-images.githubusercontent.com/11336081/101820524-93643980-3adb-11eb-8646-4f75f0d28b1e.png)

This causes the examples in the latest docs to be incorrect.

**Comment by itamarhaber** [comment]
Hi @ztaylor54 - thanks for taking the time to report this (and take a shot :)). This is a known "issue", see for example https://github.com/redis/redis-io/issues/222.

Currently, I'm thinking of adding/changing things as follows:

* Have redis.io always run the latest unstable so new commands are supported
* Add a big, shiny notice at the top of new commands (i.e. available from > latest stable) to that effect
* Disabling the interactive demo for said commands

Of course, any help would be appreciated ;) Pinging @yossigo & @oranagra wrt running unstable (would also save us time in the release process...)

**Comment by oranagra** [comment]
@itamarhaber i think that running the unstable version won't solve this (it's still confusing to see docs of something that's not yet supported).

i think there's no escape in maintaining another branch in redis-doc (maybe display it somewhere in redis.io), and merge it to the master only when doing a release.

**Comment by itamarhaber** [comment]
Ok, closing this as the (RC) version was eventually released and the example works now. WRT versioning of the docs, we'll need to work on this :)
