### ISSUE TITLE
TimeoutStartSec and TimeoutStopSec

### ISSUE THREAD

**Issue by steadybright** [redis/redis-doc#1479]
Hello,

I hope this is an easy one: I've been looking for a reference for TimeoutStartSec and TimeoutStopSec. I searched redis.io and in the documentation here, but I missed it.

Would a kind soul please point me in the right direction for these references/descriptions?

Thank you,

buzz

**Comment by itamarhaber** [comment]
Hi Buzz,

AFAIK these are standard systemd service settings. They are described at https://www.man7.org/linux/man-pages/man5/systemd.service.5.html, for example:

         TimeoutStartSec=
           Configures the time to wait for start-up. If a daemon service
           does not signal start-up completion within the configured
           time, the service will be considered failed and will be shut
           down again. The precise action depends on the
           TimeoutStartFailureMode= option. Takes a unit-less value in
           seconds, or a time span value such as "5min 20s". Pass
           "infinity" to disable the timeout logic. Defaults to
           DefaultTimeoutStartSec= from the manager configuration file,
           except when Type=oneshot is used, in which case the timeout
           is disabled by default (see systemd-system.conf(5)).

           If a service of Type=notify sends "EXTEND_TIMEOUT_USEC=...",
           this may cause the start time to be extended beyond
           TimeoutStartSec=. The first receipt of this message must
           occur before TimeoutStartSec= is exceeded, and once the start
           time has extended beyond TimeoutStartSec=, the service
           manager will allow the service to continue to start, provided
           the service repeats "EXTEND_TIMEOUT_USEC=..."  within the
           interval specified until the service startup status is
           finished by "READY=1". (see sd_notify(3)).

       TimeoutStopSec=
           This option serves two purposes. First, it configures the
           time to wait for each ExecStop= command. If any of them times
           out, subsequent ExecStop= commands are skipped and the
           service will be terminated by SIGTERM. If no ExecStop=
           commands are specified, the service gets the SIGTERM
           immediately. This default behavior can be changed by the
           TimeoutStopFailureMode= option. Second, it configures the
           time to wait for the service itself to stop. If it doesn't
           terminate in the specified time, it will be forcibly
           terminated by SIGKILL (see KillMode= in systemd.kill(5)).
           Takes a unit-less value in seconds, or a time span value such
           as "5min 20s". Pass "infinity" to disable the timeout logic.
           Defaults to DefaultTimeoutStopSec= from the manager
           configuration file (see systemd-system.conf(5)).

           If a service of Type=notify sends "EXTEND_TIMEOUT_USEC=...",
           this may cause the stop time to be extended beyond
           TimeoutStopSec=. The first receipt of this message must occur
           before TimeoutStopSec= is exceeded, and once the stop time
           has extended beyond TimeoutStopSec=, the service manager will
           allow the service to continue to stop, provided the service
           repeats "EXTEND_TIMEOUT_USEC=..."  within the interval
           specified, or terminates itself (see sd_notify(3)).

That said, if there's any relevant information missing from the docs that I'm missing here (definitely an option) please let me know.

**Comment by steadybright** [comment]
I think this does it for me. Thank you for your reply!
