### ISSUE TITLE
Question about replicas

### ISSUE THREAD

**Issue by andsk8** [redis/redis-doc#1503]
I have a question for the community.

The company I joined, they have a Redis cluster of 3 instances working in master-replica-replica configuration.

They also have these servers spread around the country, that work as read-only replicas. 

The only 3 instances that can be elected as masters, are the ones from the cluster, not the read-only replicas.

When I tried Sentinel, everything was working fine, except Sentinel was thinking that those readonly-replicas spread around the country, were also part of the cluster, so I had this problem of having those readonly-replicas being elected as masters.

Is there a way of using sentinel and saying which of the slaves can actually become a master?

Thanks

**Comment by itamarhaber** [comment]
Hello @andsk8 

I believe you're looking for information about [configuring replicas' priority](https://redis.io/topics/sentinel#replicas-priority).

Keep in mind that this issue tracker should be used for reporting bugs or proposing improvements to the Redis documentation. Questions should be directed to the [community](https://redis.io/community):

* [the mailing list](https://groups.google.com/forum/#!forum/redis-db)
* [the `redis` tag at StackOverflow](http://stackoverflow.com/questions/tagged/redis)
* [/r/redis subreddit](http://www.reddit.com/r/redis)
* [the irc channel #redis](http://webchat.freenode.net/?channels=redis) on freenode

Closing this issue.
