### ISSUE TITLE
RESP documentation requires update

### ISSUE THREAD

**Issue by boazsegev** [redis/redis-doc#1521]
It would be nice to place the [RESP3 specification](https://github.com/antirez/RESP3/blob/master/spec.md) on the [redis.io protocol documentation page](https://redis.io/topics/protocol).

The current situation is somewhat confusing for client library developers, especially considering that RESP2 is meant to be regarded as obsolete starting with Redis 6.0 and RESP3 is already the new norm.

As things stand, the redis.io documentation seems to reference an obsolete version of the RESP protocol.

Originally this was a comment in redis/redis#7163 , moved here.

**Comment by zuiderkwast** [comment]
I think a PR addressing this would be very welcome.

**Comment by oranagra** [comment]
we took the first step towards that target: https://github.com/redis/redis-doc/pull/1739
feel free to post PRs to https://github.com/redis/redis-specifications/blob/master/protocol/RESP3.md.
or even better, to https://github.com/redis/redis-doc/blob/master/topics/protocol.md

**Comment by mich-elle-luna** [comment]
https://redis.io/docs/reference/protocol-spec/ now exists with information about the versions
