### ISSUE TITLE
Add REPLCONF operation to documentation 

### ISSUE THREAD

**Issue by mahmoudashahin** [redis/redis-doc#1522]
REPLCONF is missing from the documentation 

Originally posted here https://github.com/redis/redis/issues/7163

**Comment by zuiderkwast** [comment]
This command is not supposed to be used by clients and therefore we don't want it to be documented.

It's intended to be used between replicas and primaries only. The source code mentions this:

```C
/* REPLCONF <option> <value> <option> <value> ...
 * This command is used by a replica in order to configure the replication
 * process before starting it with the SYNC command.
 * This command is also used by a master in order to get the replication
 * offset from a replica.
```

**Comment by oranagra** [comment]
added and marked as an internal command.
