### ISSUE TITLE
GEOPOS has incorrect time complexity

### ISSUE THREAD

**Issue by bouncyphoton** [redis/redis-doc#1539]
The documentation says that the time complexity for ZSCORE is `O(1)` but it's actually `O(log(N))` (assuming GEOPOS has the correct time complexity).

**Comment by itamarhaber** [comment]
Hi @bouncyphoton 

I believe the opposite is true, meaning `ZSCORE`'s TC is `O(1)`, whereas `GEOPOS`'s is an error. Would you care to make a PR to correct this against this repo's 'commands.json' file?

**Comment by bouncyphoton** [comment]
Sure! I had actually thought that `GEOPOS`'s TC was incorrect initially as well but then someone told me that they believed it was the other way around haha.

I will make a PR changing `GEOPOS`'s TC to `O(1)` for each member requested
