### ISSUE TITLE
XACK command page shows interactive command line interface, but command is blocked

### ISSUE THREAD

**Issue by avimredis** [redis/redis-doc#1551]
In redis.io, the XACK page (https://redis.io/commands/xack) shows the interactive CLI on the bottom of the screen, but under the example command, it reads "ERR Unknown or disabled command 'xack'".

**Comment by itamarhaber** [comment]
Thanks for reporting this @avimredis - this can be fixed by submitting a PR with the commands/xack.md from this repo that removes the `cli` instruction, adds an `@examples` header and includes a copy of the server's response in the body. Would you like to make that PR?

**Comment by avimredis** [comment]
Thanks Itamar I will take a look and let you know if I need any help
