### ISSUE TITLE
First example of eval man page is potentially misleading

### ISSUE THREAD

**Issue by shas-g48** [redis/redis-doc#1563]
The first example of eval script on this [page](https://redis.io/commands/eval) can potentially mislead the reader into believing that keys and arguments are 2 different ways to do the same thing.

This is because the script:
```
> eval "return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}" 2 key1 key2 first second
1) "key1"
2) "key2"
3) "first"
4) "second"
```
does not demonstrate the actual difference between these 2 types of parameters.

In other examples, they either don't make an appearance together, or are hardcoded, until the reader goes near the end of the documentation, which has some advanced examples.

I personally made this mistake after reading the documentation, as the script ends up running fine. I have 2 suggestions:
1. Introduce redis.call() and redis.pcall() earlier and use a script like this to show the difference:
`> eval "redis.call('SET', KEYS[1], ARGV[1]); redis.call('SET', KEYS[2],ARGV[2]);" 2 key1 key2 first second`
1. Or make the lines above that tell about the difference more distinctive (maybe make them bold?)

**Comment by zuiderkwast** [comment]
> 1. Introduce redis.call() and redis.pcall() earlier and use a script like this to show the difference:
>   `> eval "redis.call('SET', KEYS[1], ARGV[1]); redis.call('SET', KEYS[2],ARGV[2]);" 2 key1 key2 first second`
> 
> 2. Or make the lines above that tell about the difference more distinctive (maybe make them bold?)

Sounds good. Do you want to make a PR? Just edit this markdown file: https://github.com/redis/redis-doc/blob/master/commands/eval.md

**Comment by mich-elle-luna** [comment]
this example has been replaced in the current documentation
