### ISSUE TITLE
can someone update the redis command with proper example?

### ISSUE THREAD

**Issue by hiqsociety** [redis/redis-doc#1578]
For set :
SET key value [EX seconds|PX milliseconds] [NX|XX] [KEEPTTL] [GET]

does it mean we hv to do 

set key value ex 123 xx keepttl get <- is this the command?
or 
set key value ex 123 get <- this will suffice? 

how to use the redis as "standard compliant"? I'm writing a redis connector would like to understand how to write it properly.

**Comment by zuiderkwast** [comment]
> For set :
> SET key value [EX seconds|PX milliseconds] [NX|XX] [KEEPTTL] [GET]
> 
> does it mean we hv to do
> 
> set key value ex 123 xx keepttl get <- is this the command?
> or
> set key value ex 123 get <- this will suffice?

The second is OK, but the first is an error: You cannot have both `ex 123` and `keepttl` at the same time. Ex 123 means "the key expires after 123 seconds" and `keepttl` means "keep the current expire time of the key". You can't have both at the same time. It's clear from the syntax of [SET](https://redis.io/commands/set), which is

    SET key value [EX seconds|PX milliseconds|EXAT timestamp|PXAT milliseconds-timestamp|KEEPTTL] [NX|XX] [GET]

Everything between square brackets is optional. `X|Y` means either X or Y, not both.

It is easy to try it out using `redis-cli`:

```
$ redis-cli 
127.0.0.1:6379> set key value ex 123 xx keepttl get
(error) ERR syntax error
127.0.0.1:6379> set key value ex 123 get
(nil)
```

> how to use the redis as "standard compliant"? I'm writing a redis connector would like to understand how to write it properly.

I'm not sure what you mean, but if you accept any command as an array of strings (called for example like `redis.command(["SET", "foo", "bar", "XX"])`, then your connector doesn't need to know all the details of all the commands.

If you want to have more control, perhaps you want to create a `set` function (or method) with optional parameters like `redis.set("foo", "bar", {xx, keepttl, ex=123})`. It depends which language you are using, if you can support optional named parameters, etc.

> **can someone update the redis command with proper example?**

There is already an example with EX:

    SET anotherkey "will expire in a minute" EX 60

We can't have examples of all combinations of the optional arguments, but if you want to add an example with more optional arguments present, feel free to open a PR. I don't think it's necessary though. Users are expected to understand the syntax with the `[`, `|`, `]` notation.
