### ISSUE TITLE
documented commands are not alphabetically sorted

### ISSUE THREAD

**Issue by sillyslux** [redis/redis-doc#1605]
when you start scrolling in [Command reference - Redis](https://redis.io/commands), the commands first appear to be listed in alphabetical order. But then you don't find `SCAN` until you scroll below Z. When you reach the last 20 commands, they all seem to be appended late and that somebody forgot taking care of sorting.
a) is that intentional?
b) if not, should https://github.com/redis/redis-doc/blob/master/commands.json be sorted (and then maybe better use an array instead of an object) or do you think it's better to sort when docs are generated?

**Comment by yoav-steinberg** [comment]
I think sorting upon generation is a good idea. Feel free to issue a PR.

**Comment by sillyslux** [comment]
You're right and there is already an issue for this: redis/redis-io#186.
