### ISSUE TITLE
Complexity isn't correctly documented for ZUNION / ZINTER and friends

### ISSUE THREAD

**Issue by yoav-steinberg** [redis/redis-doc#1615]
here: https://github.com/redis/redis/blob/17511df59b96bfeab8b46d474c19ec929e605bb9/src/t_zset.c#L2663 it seems that we perform a preemptive sorting based on number of input zsets. This means there's an additional O(N*log(N)) complexity here. In cases where the input contains lots of small zsets it's expected that this will be the command's bottleneck. Should we update the complexity documentation accordingly?
Is there something similar for the set commands?

@itamarhaber, @inbaryuval WDYT?

**Comment by zuiderkwast** [comment]
This seems to be fixed already, at least for ZINTER, so I guess this issue can be closed.

I noticed that there is a similar sorting for SINTER though, so maybe that complexity should be updated too?

An option could be to record the minimum cardinality or the sum of cardinalities (depending on command) in advance and skip the sorting under certain conditions. We already have a loop over the keys before the sorting where we can record the cardinalities. When we skip sorting, we could instead move the smallest set to front in O(M) time which might be almost as good as sorting (for sinter).

This an be done for Zset and Set commands.

**Comment by yoav-steinberg** [comment]
I think the initial optimization step of sorting the input sets by size isn't part of the current complexity. Need to fix it to something like (and in all other relevant places too):
```diff
diff --git a/commands.json b/commands.json
index 66aa870..23ae017 100644
--- a/commands.json
+++ b/commands.json
@@ -4332,7 +4332,7 @@
   },
   "ZINTER": {
     "summary": "Intersect multiple sorted sets",
-    "complexity": "O(N*K)+O(M*log(M)) worst case with N being the smallest input sorted set, K being the number of input sorted sets and M being the number of elements in the resulting sorted set.",
+    "complexity": "O(K*log(K))+O(N*K)+O(M*log(M)) worst case with N being size of the smallest input sorted set, K being the number of input sorted sets and M being the number of elements in the resulting sorted set.",
     "arguments": [
       {
         "name": "numkeys",
```
