### ISSUE TITLE
ERR ERR wrong number of arguments for 'pexpire' command

### ISSUE THREAD

**Issue by benbro** [redis/redis-doc#1620]
The examples in the [pexpire](https://redis.io/commands/pexpire) docs page have errors:
```
redis>  PEXPIRE mykey 1000 XX
ERR ERR wrong number of arguments for 'pexpire' command
```

**Comment by itamarhaber** [comment]
Hi @benbro 

Thanks for reporting this. This isn't a "real" issue in the sense that the extended form of `PEXPIRE` is going to be a part of Redis v7. The website is running the latest stable (6.2.5), so this error is expected and will be resolved once v7 is released.

**Comment by benbro** [comment]
Thanks for the explanation. Do you want me to close this issue?

**Comment by enjoy-binbin** [comment]
ohh. I thought the problem was this (the output inconsistent)
```
127.0.0.1:6379> PEXPIRE myke
(error) ERR wrong number of arguments for 'pexpire' command
```
