### ISSUE TITLE
"https://redis.io/commands" "Filter by group:" Dropdown Select  any command type not found swapdb command!

### ISSUE THREAD

**Issue by startjava** [redis/redis-doc#1629]
swapdb command parent type is who???

**Comment by oranagra** [comment]
isn't it part of the "server" group?
https://redis.io/commands#server

**Comment by startjava** [comment]
haha&nbsp; oh oh oh thank you ! very !






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redis/redis-doc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redis/redis-doc] "https://redis.io/commands" "Filter by group:" Dropdown Select  any command type not found swapdb command! (#1629)





 
isn't it part of the "server" group?
 https://redis.io/commands#server
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
