### ISSUE TITLE
SINTERCARD examples is not working

### ISSUE THREAD

**Issue by roharon** [redis/redis-doc#1651]
SINTERCARD command example is not working.

![image](https://user-images.githubusercontent.com/4939738/133881648-90c5775d-08a3-4e0f-80cb-790e76cef421.png)

**Comment by itamarhaber** [comment]
Hello @roharon 

Thank you for being vigilant and responsible. This is expected as `SINTERCARD` is a Redis v7 command, and that version is yet to be released. Once v7 is made public, the docs will resolve themselves.

**Comment by itamarhaber** [comment]
Closing as resolved (v7 was released)
