### ISSUE TITLE
Update COMMAND and ACL docs

### ISSUE THREAD

**Issue by guybe7** [redis/redis-doc#1669]
Update redis.io by the changes of https://github.com/redis/redis/pull/9504 and https://github.com/redis/redis/pull/8324
 
1. The output COMMAND INFO has two new elements:
   -   Key specs (maybe requires a new topic?)
   -   Subcommands
2. New subcommand COMMAND LIST
3. ACL now has a new ID per subcommand, it's possible to block and allow subcommands

**Comment by oranagra** [comment]
i think we can hold off the COMMAND command changes till after https://github.com/redis/redis/issues/9359 is done.
but i do wanna take care of item 3 right away.
i.e. reflect the changes https://github.com/redis/redis/pull/9504 made to redis.conf here (with a note that these changes are applicable only starting v7.0)

**Comment by guybe7** [comment]
https://github.com/redis/redis-doc/pull/1697
