### ISSUE TITLE
Missing embstr on OBJECT ENCODING documentation

### ISSUE THREAD

**Issue by tallesl** [redis/redis-doc#1692]
Currently the documentation of `OBJECT ENCODING` doesn't mention the `embstr` encoding:

> Strings can be encoded as raw (normal string encoding) or int (strings representing integers in a 64 bit signed interval are encoded in this way in order to save space).

**Comment by mich-elle-luna** [comment]
embstr has been added to the object encoding doc page https://redis.io/commands/object-encoding/
