### ISSUE TITLE
Overlap of Sidenav Redlock documentation

### ISSUE THREAD

**Issue by maxwellsmart84** [redis/redis-doc#1708]
As you can see on 

https://redis.com/redis-best-practices/communication-patterns/redlock/

There is overlap on the side navigation bar and the copy on this page/view:
Browser: Chrome 
Version 96.0.4664.93 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/14876902/145468700-2ffdc511-d189-4332-b25d-9276d05e5e08.png)

**Comment by itamarhaber** [comment]
Hello @maxwellsmart84 

Thanks for noticing the glitch and making a report. This repo, however, is what powers the redis.io website, whereas redis.com's lives at https://github.com/RedisLabs/redislabs-docs, so please resubmit.

Closing this, but ccing @lanceleonard
