### ISSUE TITLE
[BUG]Typo in tuturial website

### ISSUE THREAD

**Issue by ffeiDing** [redis/redis-doc#1712]
In https://redis.io/topics/data-types-intro:

>  sadd deck C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 CJ CQ CK
   D1 D2 D3 D4 D5 D6 D7 D8 D9 D10 DJ DQ DK H1 H2 H3
   H4 H5 H6 H7 H8 H9 H10 HJ HQ HK S1 S2 S3 S4 S5 S6
   S7 S8 S9 S10 SJ SQ SK
   (integer) 52 

![image](https://user-images.githubusercontent.com/25948553/146108675-5ea1717e-bfe0-40c2-887c-6f4aee87a14b.png)

There should be fewer spaces at the beginning of the second line (before (integer 52)). This is a very small bug :D

**Comment by yoav-steinberg** [comment]
@ffeiDing can you issue a PR?

**Comment by enjoy-binbin** [comment]
> sadd deck C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 CJ CQ CK
      D1 D2 D3 D4 D5 D6 D7 D8 D9 D10 DJ DQ DK H1 H2 H3
      H4 H5 H6 H7 H8 H9 H10 HJ HQ HK S1 S2 S3 S4 S5 S6
      S7 S8 S9 S10 SJ SQ SK
    (integer) 52

so is this correct? i happen to see it, let me fix it
