### ISSUE TITLE
Ping command returns either Simple String or Bulk String response based on argument.

### ISSUE THREAD

**Issue by crackthecodeabhi** [redis/redis-doc#1727]
Hi, the Ping command returns Simple string +PONG if no argument is given to ping,
else it returns the message as bulk string message.

```
ping server
$6
server
```
Should the return value in the [Ping](https://github.com/redis/redis-doc/blob/master/commands/ping.md) doc be updated ?

Observed this on Redis 6.2.6

**Comment by itamarhaber** [comment]
Hello @crackthecodeabhi 

Thanks for noting and yes, a fix to the reply's description is definitely warranted. Would you submit the PR?
