### ISSUE TITLE
LPOP key [count] returns Null Bulk reply instead of Null array reply.

### ISSUE THREAD

**Issue by crackthecodeabhi** [redis/redis-doc#1734]
LPOP (https://redis.io/commands/lpop) with count argument since 6.2.0 returns Null bulk reply instead of array null reply.

> When called with the count argument:

> Array reply: list of popped elements, or nil when key does not exist.

When running against Redis 6.2.6, we get

> LPOP NONEXISTINGLIST 10 
> $-1

instead of 

> "*-1\r\n" 

which is a null array, as documented. 

Does the LPOP key [count] always return Bulk Null reply when no list exists to pop from regardless of count is provided or not?

**Comment by yoav-steinberg** [comment]
@crackthecodeabhi This is indeed either a documentation overlook or a bug in the code. Any chance you can open an issue (or even better a PR) in the https://github.com/redis/redis repo? The we can decide if this needs to be fixed in the code or in the docs (I'm for the code).

**Comment by enjoy-binbin** [comment]
fixed it in: https://github.com/redis/redis/issues/10089 https://github.com/redis/redis/pull/10095
