### ISSUE TITLE
Perhaps we should mention the --json output here too. It's new in 7.0 IIRC.

### ISSUE THREAD

**Issue by banker** [redis/redis-doc#1767]
Perhaps we should mention the --json output here too. It's new in 7.0 IIRC.

_Originally posted by @zuiderkwast in https://github.com/redis/redis-doc/pull/1755#discussion_r794006895_

**Comment by mich-elle-luna** [comment]
I don't understand this request from looking at the linked comment, please re-open with details and doc pages to change, or submit a PR if still needed.
