### ISSUE TITLE
Formally specify how to issue a security report

### ISSUE THREAD

**Issue by banker** [redis/redis-doc#1768]
Current text reads:

"For security-related contacts, open an issue on GitHub, or when you feel it
is really important to preserve the security of the communication, use the
GPG key at the end of this document."

Can we confirm that this is the official process?

**Comment by madolson** [comment]
More or less yeah, we also have more information here: https://github.com/redis/redis/security/policy. Seems like they should be merged a bit since we don't have the GPG key linked from the policy.

**Comment by itamarhaber** [comment]
I believe we do have that key somewhere - @yossigo please confirm.

**Comment by yossigo** [comment]
@itamarhaber We do, you should as well.

**Comment by banker** [comment]
Thanks, @madolson, @yossigo, and @itamarhaber. I'll integrate this into the docs with a new PR.

**Comment by mich-elle-luna** [comment]
key is here https://redis.io/docs/management/security/ closing as complete, please re-open if needed
