### ISSUE TITLE
Sentinel file handle tree was not released

### ISSUE THREAD

**Issue by xtxdfl** [redis/redis-doc#1817]
In the Sentinel mode of Redis, when the server and the client are connected, the client's request is released after completion, but the number of requests on the server is not released normally, and the state is still establishing the connection. The number of Clinet clients and the client list queried in the Redis command line are in normal state
Version for 3.0.4

**Comment by mich-elle-luna** [comment]
I don't understand the requested change to docs in this issue, closing.
