### ISSUE TITLE
one syntax  error in 5.0 conf

### ISSUE THREAD

**Issue by saffraan** [redis/redis-doc#1825]
a little error:

    # Normally it is useful to have an HZ value which is proportional to the
    # number of clients connected. This is useful in order, for instance, to
    # avoid too many clients are processed for each background task invocation
    # in order to avoid latency spikes.
    #
    # Since the default HZ value by default is conservatively set to 10, Redis
    # offers, and enables by default, the ability to use an adaptive HZ value
    # which will temporary raise when there are many connected clients.
    #
    # When dynamic HZ is enabled, the actual configured HZ will be used as
    # as a baseline, but multiples of the configured HZ value will be actually
    # used as needed once more clients are connected. In this way an idle
    # instance will use very little CPU time while a busy instance will be
    # more responsive.
    dynamic-hz yes

When dynamic HZ is enabled, the actual configured HZ will **be used as as a baseline**

**Comment by enjoy-binbin** [comment]
yes, it is indeed a error, it was fixed in https://github.com/redis/redis/commit/d9de9d5
but i guess we won't backport such a small typo fix :)

**Comment by madolson** [comment]
Agreed.
