### ISSUE TITLE
INCR command page broken

### ISSUE THREAD

**Issue by kappa7194** [redis/redis-doc#1829]
The page for the `INCR` command displayed in the site is broken and doesn't match what's previewed in the repository.

[This is what the site is showing.](<https://user-images.githubusercontent.com/1249988/160584038-b34c8b03-709d-4ce7-9c24-85d458426aed.png>)

[This is what the repository previews.](<https://user-images.githubusercontent.com/1249988/160584085-9eceeeeb-943b-4a3a-81ee-377387bba814.png>)

The Markdown code in the repository seems fine.

Maybe the script that generates the page is chocking because there's code after the `@examples` section?

**Comment by itamarhaber** [comment]
Hi @kappa7194 - thanks for taking the time to report this. The issue was with buggy scripting indeed, but it is now fixed. Closing.
