### ISSUE TITLE
Redis latency troubleshooting guide links lead to the same page

### ISSUE THREAD

**Issue by Dysar** [redis/redis-doc#1836]
On this page: https://redis.io/docs/manual/troubleshooting/ 2 links to the troubleshooting guide lead to the same page, not the expected guide.

**Comment by avimredis** [comment]
@itamarhaber the server is responding with a status code `301 (Moved Permanently)`. The desired page does exist at https://redis.io/docs/reference/optimization/latency/ but when trying to access this page using the markdown alias of /topics/latency (which is what the link is attempting) it redirects back to the Troubleshooting page. I've dug through the code that I have access to and I don't see anything that's creating the redirect. It's possible that the nginx server has some redirect on this specific page for some reason.

**Comment by nermiller** [comment]
It looks like this issue has been fixed. Please help us by continuing to report any issues you find. Thank you.
