### ISSUE TITLE
ACL

### ISSUE THREAD

**Issue by jhelbaum** [redis/redis-doc#1846]
The link  [Access Control List](https://redis.io/topics/acl) is broken.

**Comment by avimredis** [comment]
@jhelbaum Is this the page you are looking for? Is there a specific place where the link is misdirecting? 
https://redis.io/docs/manual/security/acl/

**Comment by Skn0tt** [comment]
here's a page that links there: https://redis.io/commands/acl/

looking at the code, it seems something about the alias system doesn't work as intended.

**Comment by jhelbaum** [comment]
Sorry, I assumed that "Create documentation issue" would include a link to the source of the error.

Yes, https://redis.io/commands/acl/ points to a bad link. So do https://redis.io/commands/acl-setuser/ and https://redis.io/docs/manual/sentinel/

Maybe there are others.

**Comment by banker** [comment]
All of these links are working for me. Are you still seeing the issue @jhelbaum ?

**Comment by Skn0tt** [comment]
when I click at the link on https://redis.io/commands/acl/, it leads me to something about TLS security, which doesn't seem right

**Comment by avimredis** [comment]
@itamarhaber The link here was fixed but redirects to the wrong address

**Comment by itamarhaber** [comment]
Thanks all - @nermiller let's try to tackle this one too.

**Comment by nermiller** [comment]
Yup, I'll take this on
