### ISSUE TITLE
ACL: Merge conflict

### ISSUE THREAD

**Issue by breyed** [redis/redis-doc#1848]
The public page for ACL is inadvertently showing a merge conflict as a section header [here](https://redis.io/docs/manual/security/acl/#it-is-active-has-a-password-and-can-access-key-names-starting-with-the-string-cached-with-the-getcommandsget-command):

> <<<<<<< HEAD:docs/manual/acl.md This example user cannot do anything. Let's try to define the user so that it is active, has a password, and can access key names starting with the string "cached:" with the [GET](https://redis.io/commands/get) command.

**Comment by enjoy-binbin** [comment]
i checked and it's normal now
