### ISSUE TITLE
TIME command should be allowed in the interactive cli

### ISSUE THREAD

**Issue by sumanth-sure** [redis/redis-doc#1850]
TIME Command example is misconfigured.
https://redis.io/commands/time/

**Comment by CwjXFH** [comment]
What's the meaning?

**Comment by itamarhaber** [comment]
Thank you @sumanth-sure for noting and reporting the issue.

I've opened another issue in the relevant repo to track this: https://github.com/redis/redis-clinterwebz/issues/6

**Comment by itamarhaber** [comment]
Fixed by https://github.com/redis/redis-clinterwebz/pull/8
