### ISSUE TITLE
Online client does not seem to work

### ISSUE THREAD

**Issue by hokjoung** [redis/redis-doc#1857]
The online client provided in the docs does not seem to work
![SET___Redis](https://user-images.githubusercontent.com/20453955/162173759-31377183-b94c-49d2-9c3d-2e3cfbaa769a.png)

**Comment by itamarhaber** [comment]
Hi @hokjoung - thanks for reporting. Will shortly be fixed.

/cc @avimredis

**Comment by gozeloglu** [comment]
I faced this problem with all commands that I tried. I tried STRING commands.

**Comment by itamarhaber** [comment]
@hokjoung @gozeloglu - this should be resolved now. Please verify.

**Comment by hokjoung** [comment]
@itamarhaber  Yes, works well. Thank you for your prompt fixes!

**Comment by itamarhaber** [comment]
Cool, thanks. Closing for now.

**Comment by gozeloglu** [comment]
@itamarhaber Yes, it works now. Thank you. If it is OK, could you share the PR of this fix? I wonder about the reason and solution of  the problem.

**Comment by itamarhaber** [comment]
@gozeloglu, of course - here's the relevant commit: https://github.com/redis/redis-clinterwebz/commit/25a00dcd2c7fd7b4c58b60394ceca3fe8716c43f#diff-0fcd5999a5474bea9102534de1f757f3a0d197a0c20149850dae4d94bf6996e8R7-R11
