### ISSUE TITLE
Libraries: Link broken for "Spring Data Redis"

### ISSUE THREAD

**Issue by austin-bowen** [redis/redis-doc#1861]
On the [Libraries page](https://redis.io/docs/libraries/#java), the homepage link to "Spring Data Redis" is broken.  It is currently this:

https://projects.spring.io/spring-data/

I think it should be updated to one of these two:

- https://spring.io/projects/spring-data
- https://spring.io/projects/spring-data-redis

**Comment by itamarhaber** [comment]
Hi @austin-bowen 

While there exists a redirect to handle that URI, I agree it would be better to update that.

**Comment by mich-elle-luna** [comment]
this page now links to spring-data-redis, closing as complete
