### ISSUE TITLE
"Checking your work" and also .github/workflows/pull_request.yml are broken

### ISSUE THREAD

**Issue by lukepalmer** [redis/redis-doc#1869]
The instructions for "Checking your work" are not usable.

This is because:
- The file named '.gems' does not exist.
- No Makefile exists

The github pull request workflow in .github/workflows/pull_request.yml appears to be based on these instructions and fails as one would expect.

**Comment by itamarhaber** [comment]
Hi @lukepalmer and thanks for the report. This is correct. These sections will need to be updated once we've finished the infrastructure-related efforts (cc @slorello89).

**Comment by mich-elle-luna** [comment]
pull-request.yml has been replaced/removed, closing
