### ISSUE TITLE
Lost one C++ redis client

### ISSUE THREAD

**Issue by zhengshuxin** [redis/redis-doc#1880]
The C++ redis client can't be seen on https://redis.io/docs/clients/#cpp but still being in https://github.com/redis/redis-doc/blob/master/clients/cpp/github.com/acl-dev/acl/tree/master/lib_acl_cpp/include/acl_cpp/redis.json . I've written this C++ redis client for many years and it has been used by many peoples for its high performance and easily to use. And the C++ redis client was shown on redis.io before, but it can't be seen there, how to be listed on redis.io?
Thanks.
---zhengshuxin

**Comment by nermiller** [comment]
It looks like this issue has been resolved. Please let us know if you encounter any other issues.
