### ISSUE TITLE
Page https://redis.io/docs/manual/pipelining/ has missing image

### ISSUE THREAD

**Issue by max-datagamma** [redis/redis-doc#1882]
The documentation page https://redis.io/docs/manual/pipelining/ refers to a graph with:

-- begin quote --
as you can see from the following graph:
-- end quote --

but the image does not exist.

**Comment by nermiller** [comment]
Hi, I think this problem may have been solved when we did a bulk update of broken links. Going to close this issue. Feel free to open any new ones should you experience problems with the docs. Thank you.
