### ISSUE TITLE
What happened to the design?

### ISSUE THREAD

**Issue by bartenra** [redis/redis-doc#1884]
Is it just me, or has the documentation become jarring? So many different font sizes, some cute web font instead of something readable, way to many words per line, headlines are ginormous (like it's meant to be read on mobile?), [bad contrast](https://contrastrebellion.com/), a lot more clicks needed to get to useful content* and distracting navigation bars on both sides.

 I don't get it.

![image](https://user-images.githubusercontent.com/77667589/164215138-67bc025e-f8d9-417a-922e-37782e82d626.png)

![image](https://user-images.githubusercontent.com/77667589/164215094-a08a4673-aa6c-4771-b504-a0b775591349.png)

* Say I want to get the basic commands. Old docs:

> Tutorials

Sounds like what I want

> [Introduction to Redis data types](https://web.archive.org/web/20210801135141/https://redis.io/topics/data-types-intro): This is a good starting point to learn the Redis API and data model.

**Done.**

New docs:

> Introduction to Redis

I guess that's it? Click. Oh, no. Scans page. Hmm, no, only links to reference pages. Back.

> [The Redis manual](https://redis.io/docs/manual/)
> A developer's guide to Redis

OK that sounds like it. Click.

> [Redis data types](https://redis.io/docs/manual/data-types/)
> Overview of the many data types supported by Redis

Doesn't sound like what I want?

**Gives up.**

**Comment by banker** [comment]
Thanks for you feedback. We've tried to address a number of these issues in the latest release. See here: https://redis.io/
