### ISSUE TITLE
RESP protocol spec - error in bulk string example

### ISSUE THREAD

**Issue by max-datagamma** [redis/redis-doc#1888]
On page https://redis.io/docs/reference/protocol-spec/#resp-bulk-strings

-- begin quote --
So the string "hello" is encoded as follows:

"$6\r\nhello\r\n"
-- end quote --

That is incorrect -- it should be:
"$5\r\nhello\r\n"

since the string contains only 5 characters.

**Comment by stevefan1999-personal** [comment]
Also noticed this when implementing the RESP protocol for the CodeCrafters challenge

**Comment by mich-elle-luna** [comment]
this is fixed now https://redis.io/docs/reference/protocol-spec/#resp-bulk-strings
