### ISSUE TITLE
Confused with why AOF "log rewrite" renames old file into new file.

### ISSUE THREAD

**Issue by lkxed** [redis/redis-doc#1890]
See the docs about "how log rewrite works": https://redis.io/docs/manual/persistence/#how-it-works-1

> Redis < 7.0.0
> ...
> Now Redis atomically renames the **old file** into the **new one**, and starts appending new data into the new file.

I don't understand. Shouldn't Redis rename the **new file** into the **old one**, not the other way around, so it can continue to write with the old filename but actually the new one?

**Comment by enjoy-binbin** [comment]
yes, the doc looks wrong. it actually do this `(rename(tmpfile,server.aof_filename)`
rename the temporary file (new one) to the old one

**Comment by lkxed** [comment]
> yes, the doc looks wrong. it actually do this `(rename(tmpfile,server.aof_filename)`
> rename the temporary file (new one) to the old one

If that, may I take the opportunity to correct the doc? Could you assign this to me?

**Comment by enjoy-binbin** [comment]
sure, go ahead and issue a PR : )
