### ISSUE TITLE
ZDIFF and ZDIFFSTORE examples on redis.io return empty sets

### ISSUE THREAD

**Issue by wodny** [redis/redis-doc#1897]
Redis 6.9.242 on redis.io [returns][1]:
```
redis:6379> ZDIFF 2 zset1 zset2
(empty array)
```
while my local Redis 6.2.6 returns:
```
127.0.0.1:6379> zdiff 2 zset1 zset2
1) "three"
```
for the same data. Same problem for [ZDIFFSTORE][2].

[1]: https://redis.io/commands/zdiff/
[2]: https://redis.io/commands/zdiffstore/

**Comment by lapwat** [comment]
Just noticed the same behaviour

**Comment by nermiller** [comment]
It looks like this problem has been fixed. Please continue to report issues with the docs. Thank you.
