### ISSUE TITLE
Redis administration - Redis setup hints error

### ISSUE THREAD

**Issue by apandourangam** [redis/redis-doc#1903]
On Redis setup hints:

_Make sure Redis won't be affected by the Linux kernel feature, transparent huge pages, otherwise it will impact greatly both memory usage and latency in a negative way. This is accomplished with the following command: echo madvise > /sys/kernel/mm/transparent_hugepage/enabled_

But when we apply this change, we still have the issue when starting Redis:

`WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.`

The fix for this issue is in the message: 
`'echo never > /sys/kernel/mm/transparent_hugepage/enabled'`

Can you confirm there is a mistake on the documentation ? Thanks

**Comment by mich-elle-luna** [comment]
as there are no other reports of this issue, closing for now
