### ISSUE TITLE
Docs/Clients page links not working

### ISSUE THREAD

**Issue by motvey** [redis/redis-doc#1910]
I can not click any links on the page to get to the respectful redis client pages. I have most recent Chrome and Mozilla updates.
The links do work for the first several rows on the page, but then <a> anchors are being overlapped by some other http elements. 
![image](https://user-images.githubusercontent.com/31589876/166344492-e798c823-d8f0-46a9-b7ae-a2eda856d413.png)

**Comment by nermiller** [comment]
Hi, this problem is fixed. We have a couple of other issues with this page that we are working on. Going to close this issue. Let us know if you have any further questions or complaints.
