### ISSUE TITLE
ZSCAN

### ISSUE THREAD

**Issue by ambarsarkar** [redis/redis-doc#1913]
Can there be any expectation of zscan returning elements in a specific order?

**Comment by zuiderkwast** [comment]
No. The scan algorithm is based on the bits inside the hashtable which is not predictable.

If you want predictable results, you can use ZRANGE, although with limit/offset, there is not the same guarantee as for zscan that all elements are returned if new elements are added between the calls.

**Comment by itamarhaber** [comment]
Closing as this question was answered.
