### ISSUE TITLE
Commands that are always used with a modifier / sub-command are hard to find / don't appear in navigation

### ISSUE THREAD

**Issue by simonprickett** [redis/redis-doc#1915]
Example, try finding the `CONFIG SET` sub-command page... https://redis.io/commands/config-set/

Start here, and you can't find it, except in the nav on the right.  It should be presented in a list in the main body of the content along with all the other commands that begin with `CONFIG`: https://redis.io/commands/config/

**Comment by nermiller** [comment]
Hi, Simon. Seems like this issue has been fixed. CONFIG no longer appears as it is the "super" command, while all CONFIG commands appear and are searchable. Going to close this issue. Let us know if you have any further questions.
