### ISSUE TITLE
HTML Heading elements cover previous elements

### ISSUE THREAD

**Issue by nerg4l** [redis/redis-doc#1917]
The following CSS rule makes heading elements cover previous HTML elements:

```
h2[id]::before, h3[id]::before, h4[id]::before, h5[id]::before {
  display: block;
  content: " ";
  margin-top: -5rem;
  height: 5rem;
  visibility: hidden;
}
```

It does not allow to click on some links or highlight some parts of the text.

OS: macOS 12.3.1
Browser: Firefox 100.0
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0

Steps to reproduce:

1. Open: https://redis.io/docs/clients/
2a. Try to select "Zig" under "Browse by language" section title.
2b. Try to highlight Redis-AS3 project description under "ActionScript" section title.

**Comment by itamarhaber** [comment]
Hi @nerg4l - thank you for reporting this issue. I'm closing it as it was already resolved.
