### ISSUE TITLE
self documented configuration for redis 7.0

### ISSUE THREAD

**Issue by masteryyh** [redis/redis-doc#1922]
hey guys I'm wondering if theres a self documented configuration file for redis 7.0?
currently theres only 6.2 for latest :(
![image](https://user-images.githubusercontent.com/9990804/167235463-96a128a2-1837-497e-8754-7d6a33063e86.png)

**Comment by enjoy-binbin** [comment]
yes, it is here: https://raw.githubusercontent.com/redis/redis/7.0/redis.conf
actually, can you issue a PR to add it?
https://github.com/redis/redis-doc/blob/master/docs/manual/config.md
