### ISSUE TITLE
ZINTERSTORE

### ISSUE THREAD

**Issue by hhow09** [redis/redis-doc#1936]
in page: https://redis.io/commands/zinterstore/

the example terminal shows wrong value. 

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/6469419/168053532-35aeabff-f482-4229-a983-a1a0ca24db33.png">

should be this instead
```
> ZRANGE out 0 -1 WITHSCORES
1) "one"
2) "5"
3) "two"
4) "10"
```

**Comment by itamarhaber** [comment]
Hi @hhow09 - thanks for creating this issue. It has been fixed via https://github.com/redis/redis-clinterwebz/pull/7, as is shown in the attached screenshot. Closing the issue as resolved.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/6059516/173200600-d13bd267-ea92-4598-8110-1b229aa3b379.png">
