### ISSUE TITLE
GETDEL

### ISSUE THREAD

**Issue by Epoch-L** [redis/redis-doc#1939]
The official docs:
redis:6379> SET mykey "Hello"
"OK"
redis:6379> GETDEL mykey
"Hello"

The practical:
127.0.0.1:6379> SET mykey "Hello"
OK
127.0.0.1:6379> getdel mykey
(error) ERR unknown command `getdel`, with args beginning with: `mykey`, 

inconsistent with official docs!

**Comment by ilovcoding** [comment]
`GETDEL`  required Redis version 6.2.3 or above , you can use info in redis-cli to get redis version information 。 
![image](https://user-images.githubusercontent.com/34740295/168417582-b46044d4-ed0b-469e-9a9c-3400abfeb28c.png)

**Comment by itamarhaber** [comment]
Hello @Epoch-L 

As @ilovcoding (thanks!) had explained, this error message is consistent with a server running a lower version of Redis. Please verify that you're using the correct version. Closing this for now, but feel free to reopen if needed.
