### ISSUE TITLE
Install Redis on Windows

### ISSUE THREAD

**Issue by langens-jonathan** [redis/redis-doc#1979]
Hey

The using redis on windows documentation page (https://redis.io/docs/getting-started/installation/install-redis-on-windows/) hints at using this ppa:
sudo apt-add-repository ppa:redislabs/redis

However the documentation for that ppa states not to use it anymore: https://launchpad.net/~redislabs/+archive/ubuntu/redis

I am wondering if I should follow the ppa docs or the guide?

Thanks 
Jonathan

**Comment by itamarhaber** [comment]
Hi @langens-jonathan - thanks for creating this issue.

We've retired Launchpad PPA in favor of the `packages.redis.io` solution, as the latter allows us to support multiple versions of Redis. I've made an attempt to fix this via #1995 - please lmk if that works for you.
