### ISSUE TITLE
Is there no information about Redis RDB Version History and  Redis RDB Dump File Format

### ISSUE THREAD

**Issue by chengshanbin** [redis/redis-doc#1998]
https://github.com/sripathikrishnan/redis-rdb-tools/blob/master/docs/RDB_Version_History.textile 
https://github.com/sripathikrishnan/redis-rdb-tools/wiki/Redis-RDB-Dump-File-Format

**Comment by itamarhaber** [comment]
Hello @chengshanbin 

The project's docs do not include the RDB's format and versions history at this time. As far as I know, the only place one can refer to is the code base for this information. Do you have any specific questions or needs regarding the format?

**Comment by nermiller** [comment]
We're closing this issue. If you need further information or additional guidance, we'll reopen the issue.
