### ISSUE TITLE
CLIENT INFO command... example fails as the user has no permissions to run this command.

### ISSUE THREAD

**Issue by simonprickett** [redis/redis-doc#2000]
On the `CLIENT INFO` command page, the example CLI fails as the user has no permissions to run the command.

See: https://redis.io/commands/client-info/

<img width="900" alt="Screen Shot 2022-06-17 at 11 08 43 AM" src="https://user-images.githubusercontent.com/94062/174277666-2d1394ac-78bb-409b-8502-94e9f9ed0afd.png">

**Comment by itamarhaber** [comment]
Fixed via https://github.com/redis/redis-clinterwebz/pull/14
