### ISSUE TITLE
Purpose of XADD LIMIT option?

### ISSUE THREAD

**Issue by SalesFeed** [redis/redis-doc#2010]
What exactly is the purpose of the LIMIT option?
Thanks.

**Comment by itamarhaber** [comment]
Hi @SalesFeed!

From the [`XADD` man page](https://redis.io/commands/xadd/#capped-streams):

> XADD incorporates the same semantics as the [XTRIM](https://redis.io/commands/xtrim) command - refer to its documentation page for more information.

From the [`XTRIM` man page](https://redis.io/commands/xtrim):

> Another way to control the amount of work done by the command when using the ~, is the LIMIT clause. When used, it specifies the maximal count of entries that will be evicted. When LIMIT and count aren't specified, the default value of 100 * the number of entries in a macro node will be implicitly used as the count. Specifying the value 0 as count disables the limiting mechanism entirely.

Makes sense?

**Comment by SalesFeed** [comment]
@itamarhaber Thanks, I somehow missed the 'same semantics as XTRIM'-part.
