### ISSUE TITLE
Typo in ACL documentation

### ISSUE THREAD

**Issue by noahehall** [redis/redis-doc#2022]
- [on the ACL doc page](https://redis.io/docs/manual/security/acl/)
- alternative to ACL LIST ... designed for computers
- while ACL LIST... more human readable
  - should this say ACL GETUSER ?
  
> Things are working as expected. In order to inspect the configuration of the user alice (remember that user names are case sensitive), it is possible to use an alternative to [ACL LIST](https://redis.io/commands/acl-list) which is designed to be more suitable for computers to read, while [ACL LIST](https://redis.io/commands/acl-list) is more human readable.

**Comment by enjoy-binbin** [comment]
yes, look like you are right
can you make a PR to fix it (in this redis-doc repo)?
