### ISSUE TITLE
ZRANGEBYLEX still used in reference document inspite of it is deprecated command on 6.2.0

### ISSUE THREAD

**Issue by roharon** [redis/redis-doc#2043]
`ZRANGEBYLEX` command is regarded as deprecated on Redis 6.2.0.
But, it is still used on  `Lexicographical indexes` reference document.

https://redis.io/docs/reference/patterns/indexes/#lexicographical-indexes

**Comment by itamarhaber** [comment]
Hi @roharon - thanks for pointing this out. I agree this can and should be updated - would you like to contribute a PR that fixes this?

**Comment by roharon** [comment]
Of course.

**Comment by itamarhaber** [comment]
Resolved via #2045
