### ISSUE TITLE
Install Redis on Linux

### ISSUE THREAD

**Issue by fmelink** [redis/redis-doc#2050]
Instructions break apt when lsb_release is not available (e.g. in Debian 9.13 on WSL2). Installing lsb-core first solves the problem.

**Comment by yossigo** [comment]
We can add a note about how to get `lsb_release` if it's missing.
Stretch is old and AFAICT not even supported by Debian anymore, so I wouldn't go too far just for that.

**Comment by itamarhaber** [comment]
Since this may also affect modern, minimal distros it is better to be safe than sorry (assuming people will RTFM ;)) - note added via #2051
