### ISSUE TITLE
CLIENT INFO

### ISSUE THREAD

**Issue by SubhrajitPrusty** [redis/redis-doc#2057]
Example just shows an error:
![image](https://user-images.githubusercontent.com/4463839/181763263-89b3ada2-4b5f-4ca9-987b-caac18650962.png)

**Comment by itamarhaber** [comment]
Hello @SubhrajitPrusty 

Thanks for noticing and reporting the issue. This known issue is being tracked in https://github.com/redis/redis-clinterwebz/issues/12 and should be resolved via https://github.com/redis/redis-clinterwebz/pull/14.

Closing this one.
