### ISSUE TITLE
time complexity in ZMPOP doc may be wrong

### ISSUE THREAD

**Issue by ZZZeno** [redis/redis-doc#2059]
Hey, I recently tried to use redis zset to implement a priority queue. When I read the DOC, I found something a little strange. The DOC said 
> Command: ZMPOP
> Time complexity: O(K) + O(N*log(M)) where K is the number of provided keys, N being the number of elements in the sorted set, and M being the number of elements popped.

I don't know why `ZMPOP` command's time complexity growth is related with `log(M)` and has linear relation with length of zset N. It should be `O(M*log(N))` by my instinct. So I did a benchmark of this command.

here is my env: 
> redis_version:7.0.4
> typescript: 4.6.2
> ioredis: 5.0.2
------------------------
here is my testing process
```typescript
   await initData(10000)

   await benchmark('zmpop max from zset1:', async () => {
       return redis.zmpop(1, 'zet1', 'MAX')
   })
   await benchmark('zpopmax from zset2', async () => {
       return redis.zpopmax('zset2')
   })
```

output was
```bash
init data starts
init 10000 data done
item count: zset1: 10000
item count: zset2: 10000
zmpop max from zset1: time cost: 414208 (ns)
zpopmax from zset2 time cost: 224768 (ns)
```

then increase data set size from 10k to 100k

output became
 ```bash
init data starts
init 100000 data done
item count: zset1: 100000
item count: zset2: 100000
zmpop max from zset1: time cost: 454912 (ns)
zpopmax from zset2 time cost: 285696 (ns)
```
Benchmark shows data set became 10 times larger, while the time cost did not increasing accordingly. So is there any thing wrong with the DOC? Or is there something wrong in my testing method?

Ref: https://redis.io/commands/zmpop/

**Comment by enjoy-binbin** [comment]
thanks for the report and it is good that you tested it
and you are right, the complexity is wrong, it was fixed in https://github.com/redis/redis/pull/11026
but we haven't synced it here (redis-doc) yet, the new release (redis) has not been released yet

**Comment by ZZZeno** [comment]
Thanks for your reply. Have a good day :)
