### ISSUE TITLE
SETEX does not show TTL as related

### ISSUE THREAD

**Issue by gnbl** [redis/redis-doc#2065]
https://redis.io/commands/setex/ (https://github.com/redis/redis-doc/edit/master/commands/setex.md) does not list "TTL" in "Related commands" despite using it in the example.

**Comment by itamarhaber** [comment]
Hi @gnbl 

Currently, the "Related Commands" are all commands that belong to the same group as the command itself. `SETEX` belongs to the "string" group, whereas `TTL` is a generic keyspace operation that belongs to the "generic" group.

I hope this makes sense and resolves the issue.

**Comment by gnbl** [comment]
Hi, if that's by design, fine - but for me as new redis user it would make sense to include TTL due to its "timeout" relation.
Maybe extend "Related Commands" to offer other relations? Just an idea. Feel free to close!

**Comment by nermiller** [comment]
@itamarhaber, I can edit as part of the restructure, since we intend to add Related at the bottom
