### ISSUE TITLE
DUMP: Example returns a utf-8 codec error.

### ISSUE THREAD

**Issue by thomas-schreiter** [redis/redis-doc#2076]
The example on the page returns an error: `(error) 'utf-8' codec can't decode byte 0xc0 in position 1: invalid start byte`. 

It doesn't look like that's intended.

Screenshot from https://redis.io/commands/dump/:
![image](https://user-images.githubusercontent.com/3344291/183780512-75e67ac0-09f9-48a1-a403-02b383005e32.png)

**Comment by itamarhaber** [comment]
Hi @thomas-schreiter - thanks for reporting this.

We're aware of this issue and are tracking it as part of https://github.com/redis/redis-clinterwebz/issues/12
