### ISSUE TITLE
"Streams Tutorial" link broken on "Redis Streams" page

### ISSUE THREAD

**Issue by Harry-Lees** [redis/redis-doc#2087]
At the bottom of [this page](https://redis.io/docs/data-types/streams/) The link "Redis Streams Tutorial" points to: https://redis.io/docs/data-types/streams-tutorial.md which doesn't exist. It should point to https://redis.io/docs/data-types/streams-tutorial/

**Comment by itamarhaber** [comment]
Hi @Harry-Lees - thanks for identifying and reporting the issue. The fix's merge is imminent.
