### ISSUE TITLE
About the description of default data size in Redis benchmark.

### ISSUE THREAD

**Issue by GlareR** [redis/redis-doc#2105]
There are some inconsistencies between the description and the code of the **default data size** in Redis benchmark.
As you can see from the first fig, the default data size in the codes is **3**, but the description of it is **2**.
This situation made us questioned by others.
![image](https://user-images.githubusercontent.com/19928321/187216979-1a0484e6-af87-4c14-a9e2-e8b1eda489cb.png)
![image](https://user-images.githubusercontent.com/19928321/187217075-68ff225a-c16f-43ac-a970-d2c69dbcca4d.png)

**Comment by nermiller** [comment]
Thank you so much for bringing this to our attention. We will fix it!
