### ISSUE TITLE
ACL SETUSER : https://redis.io/commands/acl-setuser/ - text change request

### ISSUE THREAD

**Issue by greg-pedder** [redis/redis-doc#2108]
https://redis.io/commands/acl-setuser/

ACL SETUSER virginia on allkeys +set

....Then another SETUSER call can modify the user rules:

ACL SETUSER virginia +get

"The above rule will not apply the new rule to the user virginia, so other than [SET], the user virginia will now be able to also use the [GET] command."

Shouldn't the "not" in that opening sentence be removed? 
The second SETUSER rule seems to apply that change in my local setup.

**Comment by nermiller** [comment]
Yes, that's a typo. We'll fix. Thanks for bringing it up!

**Comment by greg-pedder** [comment]
Cool.
Thanks for the quick response!
