### ISSUE TITLE
java long issue on redis

### ISSUE THREAD

**Issue by Amer-a-h** [redis/redis-doc#2119]
1- FT.CREATE bugs ON hash PREFIX 1 "bug:" SCHEMA ad_id NUMERIC user_id NUMERIC
2- hset bug:1 ad_id 1 user_id 1663073253725000092
3- ft.search bugs "@ad_id:[1,1]" return 1 user_id
results -> 
```
{
1) "1"
2) "bug:1"
3) 1) "user_id"
   2) "1663073253725000192"
}
```
it should return 1663073253725000092 not 1663073253725000192

**Comment by itamarhaber** [comment]
Hello @Amer-a-h 

Thanks for reporting this issue, but it belongs in this repo: https://github.com/RediSearch/RediSearch

Kindly open a [new issue there](https://github.com/RediSearch/RediSearch/issues/new).
