### ISSUE TITLE
Redis Streams

### ISSUE THREAD

**Issue by tdeverdiere** [redis/redis-doc#2122]
There is a typo on `tempertures:us` :
`XREAD COUNT 100 BLOCK 300 STREAMS tempertures:us-ny:10007 $`

should be
`XREAD COUNT 100 BLOCK 300 STREAMS temperatures:us-ny:10007 $`

**Comment by enjoy-binbin** [comment]
thanks for the report, can you raise a PR to fix it?

**Comment by tdeverdiere** [comment]
Yes : https://github.com/redis/redis-doc/pull/2126

**Comment by enjoy-binbin** [comment]
closing in favor of #2126
