### ISSUE TITLE
typo correction needed for XGROUP entries_read explanation

### ISSUE THREAD

**Issue by bconfident** [redis/redis-doc#2125]
The current paragraph reads:

The optional entries_read named argument can be specified to enable consumer group lag tracking for an arbitrary ID. An arbitrary ID is any ID that isn't the ID of the stream's first entry, its last entry or the zero ("0-0") ID. **This can be useful you know exactly how many** entries are between the arbitrary ID (excluding it) and the stream's last entry. In such cases, the entries_read can be set to the stream's entries_added subtracted with the number of entries.

This should be corrected to read:
**This can be useful to know exactly how many**

**Comment by nermiller** [comment]
Thanks for bringing this issue to our attention. We'll fix it!

**Comment by itamarhaber** [comment]
Thanks @bconfident, there's indeed a glitch there. Iirc, I intended writing this: "This can be useful if you know exactly how many...".

Would you like to submit a pull request to fix that?

Context: this argument is meant to be internal for replication purposes, but for completeness sake it is documented in syntax and text.
