### ISSUE TITLE
The README.md provides missleading information about the provided Angular Package. The package works for Angular 11+ and not for the old AngularJS

### ISSUE THREAD

**Issue by Pezequiel1976** [redis/redis-doc#2128]
The README.md provides missleading information about the provided Angular Package. The package works for Angular 11+ and not for the old AngularJS

_Publicación original de @alexanderfink en https://github.com/hCaptcha/hcaptcha-integrations-list/issues/65_

**Comment by itamarhaber** [comment]
Hi @Pezequiel1976 

I'm not aware of an Angular package in this project. This issue appears irrelevant so I'll be closing it, but feel free to reopen and add more information about the problem if you disagree.

**Comment by alexanderfink** [comment]
@itamarhaber Something is off here? I posted this question in another project, and somehow @Pezequiel1976 reposted it here? Maybe a bot? :o

**Comment by itamarhaber** [comment]
Nah, he's definitively hooman, see the year in the handle? Bots didn't exist back in '76 ;)
