### ISSUE TITLE
Redis trademark guidelines - article 7

### ISSUE THREAD

**Issue by zeritonius** [redis/redis-doc#2135]
On this page:
[https://redis.io/docs/about/trademark/](https://redis.io/docs/about/trademark/) 

article 7 reads:
NOTIFY US OF ABUSE. Do not make any changes to the Logo. This means you may not add decorative elements, change the colors, change the proportions, distort it, add elements or combine it with other logos.

which is exactly the text from the article 6th last paragraph.

**Comment by itamarhaber** [comment]
Hi @zeritonius - thanks for catching this. It looks like this has been there for quite some time :)

I'd assume article 7 should be deleted or changed to something like: "NOTIFY US OF ABUSE. Kindly let us know of any violations to the above"

I'll work on resolving this shortly.
