### ISSUE TITLE
Getting started with Redis

### ISSUE THREAD

**Issue by hvy22** [redis/redis-doc#2139]
`$ redis-cli ping
PONG`

**Comment by hvy22** [comment]
`$ redis-cli
redis 127.0.0.1:6379> ping
PONG
redis 127.0.0.1:6379> set mykey somevalue
OK
redis 127.0.0.1:6379> get mykey
"somevalue"`

**Comment by nermiller** [comment]
Hi! Please provide some context for this bug. Thank you so much for using Redis!

**Comment by nermiller** [comment]
I am going to close this issue. Please reopen if you're experiencing problems with the content. Thank you for using the docs!
