### ISSUE TITLE
Getting started with Redis - copy utils/redis_init_script

### ISSUE THREAD

**Issue by justincavery** [redis/redis-doc#2166]
If you installed Redis through the recommended approach found here https://redis.io/docs/getting-started/installation/install-redis-on-linux/ there is no `utils/redis_init_script` on the server that you can copy across.

**Comment by itamarhaber** [comment]
Hello @justincavery 

I'm unsure if I'm following your question and/or issue. The script mentioned above is a part of the project's source and is provided as an example. The page you're referring to is about installing packaged binaries, which come with their own scripts.
