### ISSUE TITLE
Install Redis on Linux

### ISSUE THREAD

**Issue by Damon-arch** [redis/redis-doc#2176]
Expect the procedure of installing on CentOS.

**Comment by Pezequiel1976** [comment]
> Expect the procedure of installing on CentOS.

**Comment by itamarhaber** [comment]
Hello @Damon-arch

If I'm guessing correctly, you'd like to have instructions for installing Redis on CentOS. The Redis project doesn't offer any packages for that OS, so if that's your ask I'm afraid I have to disappoint you.

**Comment by nermiller** [comment]
The description was misleading. We support Linux distributions as presented in the current docs. I've edited the description to mention Linux only,
