### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by marcia-schulman** [redis/redis-doc#2179]
This link does not go to a valid page: https://redis.io/redisearch/indexing_json

**Comment by itamarhaber** [comment]
Hello @marcia-schulman 

Thanks for reporting the issue - what page is this link from?

**Comment by itamarhaber** [comment]
Thanks @marcia-schulman - I've submitted the [fix](https://github.com/RedisJSON/RedisJSON/pull/855)

@slorello89 any idea why lychee missed that?

**Comment by mich-elle-luna** [comment]
confirmed this is fixed now https://redis.io/docs/data-types/json/
