### ISSUE TITLE
Documentation Link Returns 404

### ISSUE THREAD

**Issue by mdworkin21** [redis/redis-doc#2184]
Hello,

A link provided in the Indexing and Querying with Redis Search lesson returns a 404: https://oss.redislabs.com/redisearch/Query_Syntax/

**Comment by itamarhaber** [comment]
Hello @mdworkin21, thanks for reporting this issue.

Please provide the URL of the page with the invalid reference.

**Comment by mdworkin21** [comment]
Hello, 

Here you go: https://developer.redis.com/develop/node/nodecrashcourse/redisearch

Part of page:
![Screen Shot 2022-11-04 at 1 20 23 PM](https://user-images.githubusercontent.com/32579329/200037304-95003a9e-d03a-406f-b91c-235e5ebdbebc.png)

**Comment by itamarhaber** [comment]
@mdworkin21 thanks for the clarification.

This content lives at https://github.com/redis-developer/redis-developer.github.io/edit/master/docs/develop/node/node-crash-course/redisearch/index-redisearch.mdx - please open an issue or submit a PR there.

/cc @simonprickett

**Comment by simonprickett** [comment]
Thanks - I'll take this and fix it, track it here:

https://github.com/redis-developer/redis-developer.github.io/issues/495
