### ISSUE TITLE
is there a mechanism could limit  the max size of list ?

### ISSUE THREAD

**Issue by ldpiuaeng** [redis/redis-doc#2185]

**Comment by itamarhaber** [comment]
Hello @ldpiuaeng 

There isn't a built-in way to limit lists' (or most other data types') size. You can, however, use scripting or functions to compose the logical workflow for that. For example, the following Lua script will reject new elements if the list's size is over some threshold:

```lua
local list = KEYS[1]
local ele = ARGV[1]
local cap = ARGV[2]

if redis.call('LLEN', list) > cap then
  return redis.erro('Max size')
end
return redis.call('LPUSH', list, ele)
```

**Comment by ldpiuaeng** [comment]
get it,many thanks.
