### ISSUE TITLE
bitpos behaviour doesn't seem consistent

### ISSUE THREAD

**Issue by JeremyWildsmith** [redis/redis-doc#2207]
My understanding of the documentation and after working with bitpos is that:

For a given key x:
1. bitpos will return -1 if the specified range (defined with __start__ and __end__ arguments) is outside of bounds of the string IF "x" is defined (ie has an associated string value)
2. bitpos will return 0, ignoring the range completely, if x is undefined (has no associated string value)

It seems to me, that in the case of 2, bitpos would be more consistent to return -1, or at the lower bounds of the specified range.

At the very least, I think 2 is a notable edge-case and it should be clearly explained in the docs. I can create a merge request for the docs, but I want to ensure my understanding here is correct to begin with.

**Comment by itamarhaber** [comment]
Hello @JeremyWildsmith 

Thank you for the proposal. I believe your understanding is correct.

However. The 0 (zero) reply is consistent with other commands that are invoked on non-existent keys (e.g., `STRLEN`, `ZCARD` and the rest). I'm not sure that this needs to be mentioned here, and for every such command.

**Comment by JeremyWildsmith** [comment]
Hello,

We can justify ZCARD returning zero on an undefined key because the length of an undefined list is arguably 0 and this is intuitive. We can justify similarly for STRLEN or BITPOS with no specified range argument.

But we cannot similarly justify the return of BITPOS using a defined range constraint on an undefined key. The zero return code doesn't make sense in the context of the request made. It is not a special value (ie -1), but it directly conflicts with the constraints of the request.

I've read the documentation here several times, and this behaviour just doesn't seem intuitive. In the context of someone familiar with REDIS as a whole, the behaviour may be expected, but for a user who has just causal familiarity it doesn't seem intuitive.

Anyways, that's my case :smile:  This is just a suggestion after all.

**Comment by itamarhaber** [comment]
Thanks @JeremyWildsmith - everything you've written is valid and acceptable 👍 

FYIs @redis/core-team, although I don't see how we can change this now.

**Comment by oranagra** [comment]
i tend to agree it should have returned -1, but i also agree that changing it now would be problematic (breaking change).
if it is not clearly documented, then that's something we can easily improve.
