### ISSUE TITLE
* is not properly escaped causing texts to be italicized

### ISSUE THREAD

**Issue by hbina** [redis/redis-doc#2210]
See image:

![Screenshot from 2022-11-11 12-08-19](https://user-images.githubusercontent.com/6733660/201261367-89e3fe94-1f2e-429e-947a-6ecb835adf9d.png)

Notice how the text is italicized from what is intended to be `N * M` up until `1 * M`.

From the source `commands/dump.json` here: https://github.com/redis/redis/blob/unstable/src/commands/dump.json#L4

I can't find any resources on how to build the website myself? So I am not sure how to fix this. I think escaping the `*` will fix it but IDK about your workflow.

**Comment by itamarhaber** [comment]
Hi @hbina 

Thanks for reporting the issue - it should be fixed now. Feel free to look around that repo :)
