### ISSUE TITLE
Simplify explanation for SETEX?

### ISSUE THREAD

**Issue by hbina** [redis/redis-doc#2212]
It says that `SETEX` is equivalent to `SET` and then `EXPIRE`.
But  `SET` already have the `EX` option, so `SETEX` is also equivalent to `SET key value EX seconds` which is a lot simpler.
This removes the necessity to explain that `SETEX` is atomic yadda yadda.

**Comment by itamarhaber** [comment]
Hello @hbina 

The doc was written for `SETEX`, which (slightly) preceded `SET ... EX`, and therefore it doesn't refer to it.
That said, I agree this can be improved, would you want to submit a PR for that?

**Comment by itamarhaber** [comment]
This issue had also triggered the following change: https://github.com/redis/redis/pull/11512
