### ISSUE TITLE
SLAVEOF : extremely poor documentation of REDIS throughout the commands

### ISSUE THREAD

**Issue by nilaysahu** [redis/redis-doc#2218]
DOesnt include any mention of how databases work when one redis instance is slave of other. Infact DB is out of picture in any of the command documentation. Trying out command on local to figure out if the commands work/impact multiple DB.
Similarly for MIGRATE command. One of the most poorest form of documentation available on the planet.

**Comment by itamarhaber** [comment]
Hello @nilaysahu 

It sounds like you're unhappy with the project's state of documentation and have strong opinions as to what it should be. The docs are open and we'd appreciate any help you can give to make that happen, as we want to improve constantly.

With you permission I'll be closing this issue as it is unclear what you're asking for. Please feel free to open actionable issues and submit PRs for improvement.
