### ISSUE TITLE
XINFO STREAM FULL is undocumented

### ISSUE THREAD

**Issue by guybe7** [redis/redis-doc#2230]

**Comment by oranagra** [comment]
@guybe7 i see it is documented https://redis.io/commands/xinfo-stream/
so either i'm missing something, or this ticket is obsolete. re-open with more details if needed.

**Comment by guybe7** [comment]
the fields returned when `FULL` is given are undocumented

**Comment by mich-elle-luna** [comment]
FULL is now documented here https://redis.io/commands/xinfo-stream/

**Comment by guybe7** [comment]
@mich-elle-luna maybe i'm missing something because it appears to me that https://redis.io/commands/xinfo-stream/ has documentation of the fields returned when FULL **isn't** used

**Comment by oranagra** [comment]
to make it clear. the fact the argument appears in the command syntax isn't relevant (that info comes from the json file), and the fact the functionality of the FULL argument is described is insufficient.
we want to document the meaning of each of the fields it exposes.
