### ISSUE TITLE
Getting started with Redis

### ISSUE THREAD

**Issue by duong1998nd** [redis/redis-doc#2232]
connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete]

**Comment by itamarhaber** [comment]
Hi @duong1998nd 

It looks like you can't connect to Redis. Keep in mind that this issue tracker should be used for reporting bugs or proposing improvements to the Redis documentation. Questions should be directed to the [community](https://redis.io/community):

* [the mailing list](https://groups.google.com/forum/#!forum/redis-db)
* [the `redis` tag at StackOverflow](http://stackoverflow.com/questions/tagged/redis)
* [/r/redis subreddit](http://www.reddit.com/r/redis)
* [the irc channel #redis](http://webchat.freenode.net/?channels=redis) on freenode
