### ISSUE TITLE
TYPE

### ISSUE THREAD

**Issue by uzrnem** [redis/redis-doc#2240]
Why geo location and sorted set have same data type?

**Comment by itamarhaber** [comment]
Hello @uzrnem 

That's because both use the same data type (zset). Also note that to delete members from a geoset you need to call `ZREM`, as there's no `GEODEL` (by design, not because of incompleteness).

Similarly and for your information, bitmaps, bitfields, and hyperloglogs all use the string as their underlying type.

**Comment by uzrnem** [comment]
Hi @itamarhaber, 
First of all Thank you for your reply, I really appropriate it.

I am working on creating GUI for redis, I this case how I am going to differentiate between both data types?

**Comment by itamarhaber** [comment]
In this case (zset vs geoset) there is no programmatic way you can use to make the right choice. This could be improved (e.g. if Redis was to have different types), but it doesn't solve the larger problem IMO.

If I were creating a GUI like yours, I'd probably follow the following reasoning:

1. Data comes in many formats
2. Redis' types contain structured data - the data obeys no. 1
3. The choice of how to view the data should belong to the user

Here's an example - suppose you have a string key with this in it: `{"a":"b"}`. By default, it should be displayed as a string, but I would like to have the user be able to switch to "JSON view" to get better formatting. Or the contents could be a png file... or perhaps hex is needed.... (as a bonus, I would maybe try guessing the rendered based on the content).

Continuing with this mindset, I'd render zsets as members and scores by default, but allow the user to switch the view to geo table/map/whatever.

I hope this makes sense.

**Comment by uzrnem** [comment]
Hi @itamarhaber,
I was thinking same to give option to user to switch from sortedSet to GeoLocation.
My queries are solved, Thank you :)
