### ISSUE TITLE
Redis security

### ISSUE THREAD

**Issue by simonprickett** [redis/redis-doc#2241]
On the Redis security page on redis io (https://redis.io/docs/management/security/):

* The title should be "Redis Security" not "Redis security"
* In the "Authentication" section, this is no longer true as access control lists were introduced in Redis 6.0:

>While Redis does not try to implement Access Control, it provides a tiny layer of optional authentication that is turned on by editing the redis.conf file.

**Comment by itamarhaber** [comment]
Hello @simonprickett and thanks for spotting these. Would you like to make a PR that addresses these issues?

**Comment by simonprickett** [comment]
@itamarhaber yes, want to assign this to me so I can track it?  Thanks.
