### ISSUE TITLE
GETRANGE

### ISSUE THREAD

**Issue by mukesh191** [redis/redis-doc#2244]
Hi Team,

there is some error on below page , could you please check and update ? 

https://redis.io/commands/getrange/

redis> SET mykey "This is a string"
Failed to fetch
redis> GETRANGE mykey 0 3
Failed to fetch

Output should be - 

 > GETRANGE mykey 0 3 
"This"

**Comment by itamarhaber** [comment]
Hello @mukesh191 

Thanks for reporting. The page appears to work fine on my laptop, so I can't reproduce the issue. Please let us know if the issue persists, and if so also look in your browser's developer console and see if there are any errors.

**Comment by mukesh191** [comment]
Hey @itamarhaber,  

Now it's working fine 

thanks for responding
