### ISSUE TITLE
Redis reference lacks information about quoting and other format-on-the-wire details

### ISSUE THREAD

**Issue by PerMildner** [redis/redis-doc#2247]
I cannot seem to find any details about how "strings" are quoted etc. when passing them as arguments to commands.

There are some examples that seem to use quoting, e.g. `\"` for embedded backslashes, but I see no _specification_ anywhere.

A proper specification of the protocol details would help when writing a new client.

**Comment by itamarhaber** [comment]
Hello @PerMildner 

I'd like to understand what's missing and see if the gap can be closed, but I'm unsure if I understand the ask.

The [protocol page](https://redis.io/docs/reference/protocol-spec/) describes the protocol as follows:

> Redis uses RESP as a request-response protocol in the following way:
> * Clients send commands to a Redis server as a RESP Array of Bulk Strings.
> * The server replies with one of the RESP types according to the command implementation.

Bulk Strings do not require any escaping. So... what am I missing? :)

**Comment by PerMildner** [comment]
@itamarhaber Thanks, you are entirely correct. The text you pointed to does indeed contain the information I need (*). I do not know how I missed that, but presumably because I did not notice the entry in the table-of-contents to the right and started reading from the top of the document and gave up (I think I had already tried in vain to find the information in several earlier documents on the reference page).

(*) One related issue is that the RESP protocol seems to be legacy (in favor of RESP3) which should perhaps be mentioned somewhere and presumably affects which specification should be used when producing commands.

I think you can just close this issue as PEBKAC :-)

**Comment by itamarhaber** [comment]
ROTFLMAO WRT PEBKAC - we're all that and even worse :P

* PTAL #2203 - inputs are more than welcome.
