### ISSUE TITLE
@Ezequiel198

### ISSUE THREAD

**Issue by Pezequiel1976** [redis/redis-doc#2262]
https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=197428

_Publicación original de @chrmarti en https://github.com/microsoft/vscode/issues/169608_

_Publicación original de @Pezequiel1976 en https://github.com/google-developer-training/basic-android-kotlin-compose-training-cupcake/issues/26_

**Comment by itamarhaber** [comment]
This issue seems to have been created by mistake. I'm closing it, but please feel free to reopen/create a new issue with the relevant details.
