### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by rafalkkk** [redis/redis-doc#2265]
How should this code be started?
```
WATCH mykey
val = GET mykey
val = val + 1
MULTI
SET mykey $val
EXEC
```
redis-cli returns error, also if saved as lua it fails

**Comment by itamarhaber** [comment]
Hello @rafalkkk 

This example uses pseudo code, which isn't meant to be run as is, but rather as reference for implementation in your programming language of choice.

**Comment by rafalkkk** [comment]
Thank you!
