### ISSUE TITLE
LREM

### ISSUE THREAD

**Issue by sunqb** [redis/redis-doc#2280]
when i put a object into list，it can not be deleted

eg:  `<html>
<body>

[{"businessType":1,"linkUrl":"http://www.baidu.com","status":1,"taskId":"139"}]
--

</body>
</html>`

**Comment by itamarhaber** [comment]
Hello @sunqb 

Please provide the full details about the issue.

**Comment by sunqb** [comment]
the bug is related to redistemplate , i will close this issue
