### ISSUE TITLE
INFO Sentinel not documented

### ISSUE THREAD

**Issue by voxel01** [redis/redis-doc#2283]
for the info command there is currently no documentation about the sentinel section

**Comment by itamarhaber** [comment]
Thanks @voxel01 - it looks like you're correct, this information is missing from https://redis.io/commands/info/.

Would you like to submit a PR to fix this issue?

**Comment by voxel01** [comment]
I would, if I could, but I think I am not qualified to do that.

**Comment by enjoy-binbin** [comment]
thanks for the report, Sentinel-related documents have been relatively missing, I tried adding it in the PR above
