### ISSUE TITLE
LINSERT returns undocumented 0 when the key does not exist

### ISSUE THREAD

**Issue by jimsnab** [redis/redis-doc#2288]
`LINSERT` return documentation says:

```
Return
Integer reply: the length of the list after the insert operation, or -1 when the value pivot was not found.
```

It turns out this command will return 0 (the length of the list) when the key does not exist - and insert operation was not done.

The return value should be clarified, so that application writers know to look for <= 0 for pivot not found, instead of just -1.

Other commands may have similar issues, as key existence seems to take precedence over the operation's specific meaning of return value.

**Comment by enjoy-binbin** [comment]
thanks for the report, indeed, we need to document this

> Other commands may have similar issues, as key existence seems to take precedence over the operation's specific meaning of return value.

This is indeed a problem, I think it has been dealt with several times
