### ISSUE TITLE
Tools other than CLI, GUI and Proxy

### ISSUE THREAD

**Issue by zuiderkwast** [redis/redis-doc#2295]
There are some (probably many) tools that don't fit in the categories we have on the Tools page. I'm thinking about these:

* https://github.com/oliver006/redis_exporter Promethius metrics exporter
* https://github.com/IBM/operator-for-redis-cluster Kubernetes operator for Redis Cluster

Is it possible to add an "Other" category on the Tools page? Can I simply create a new directory under [tools/](https://github.com/redis/redis-doc/tree/master/tools)?

@itamarhaber @nermiller WDYT?

**Comment by itamarhaber** [comment]
Hi @zuiderkwast 

I'm ok with it. On top of the directory (and jsons), also add the new category to tool_types.json.
