### ISSUE TITLE
List commands that remove items do not mention what happens on empty list

### ISSUE THREAD

**Issue by valkum** [redis/redis-doc#2319]
Currently, the docs for commands that remove items from a list, such as `LPOP` or `LREM`, do not mention that the key is removed when the number of list items reaches 0.
I am uncertain if this is a guarantee that is given. I could not find a matching issue in this repo and only found some stackoverflow answers hinting this might be the normal behavior.
I also checked the Redis ebook which also did not handle this case explicitly.

The only hint towards this behavior is given in `LREM` as far as I can see:
> Note that non-existing keys are treated like empty lists, so when key does not exist, the command will always return 0.

If this is indeed a guaranteed behavior, would you accept a PR that adds something like the following to the respective commands?
> If the number of remaining items becomes zero after executing this command, the specified key gets removed.

LPOP, LMPOP, LREM, LMOVE, LTRIM, RPOP, and RPOPFLUSH

**Comment by itamarhaber** [comment]
Hi @valkum 

This behavior is introduced in the [tutorial](https://redis.io/docs/data-types/tutorial/#automatic-creation-and-removal-of-keys):

> ... It is Redis' responsibility to delete keys when lists are left empty, or to create an empty list if the key does not exist ... This is not specific to lists, it applies to all the Redis data types composed of multiple elements -- Streams, Sets, Sorted Sets and Hashes.

Instead of trying to add a note to each command, I wonder if we can make the above more prominent.
