### ISSUE TITLE
ZRANK command don't supports the `WITHSCORE` option

### ISSUE THREAD

**Issue by xiaoyaobishizhe** [redis/redis-doc#2323]
This command don't supports the `WITHSCORE` option in newest Redis version 7.0.8, but the newest documentation contains this option.

Also, "Examples" block in documentation of `ZRANK` command has an error response.

![image](https://user-images.githubusercontent.com/77526176/218707068-a7be65e8-9857-4776-8bc0-23942a2df202.png)

**Comment by enjoy-binbin** [comment]
Hi

> History
> Starting with Redis version 7.2.0: Added the optional WITHSCORE argument.

At the bottom we have a history section, WITHSCORE will be released in 7.2

and the example, i guess the website cli is runing in a redis7 instrance, not 7.2 (or others), so the example is wrong. it will be fine when 7.2 is release (we're planning to release 7.2 RC1 in March)
