### ISSUE TITLE
404 for RedisInsight documentation

### ISSUE THREAD

**Issue by tao12345666333** [redis/redis-doc#2325]
https://redis.io/docs/stack/insight/

![2023-02-15 17-07-39屏幕截图](https://user-images.githubusercontent.com/3264292/218983117-3d9edf9d-01cc-4ea6-bb6c-fbb5f007c141.png)

**Comment by itamarhaber** [comment]
Hello @tao12345666333 

Thanks for catching this. May I ask how you got to that page?
