### ISSUE TITLE
redis subscribing to keyspace cannot receive data

### ISSUE THREAD

**Issue by rollbor** [redis/redis-doc#2331]
In the docker container deployment environment, the subscription update message cannot be received, but there is no problem when the local host is running. Do you guess that the network is blocked at any link?

**Comment by itamarhaber** [comment]
Hello @rollbor 

This indeed sounds like a networking issue in your deployment.

Keep in mind that this issue tracker should be used for reporting bugs or proposing improvements to the Redis documentation.

Questions should be directed to the [community](https://redis.io/community):

* [the mailing list](https://groups.google.com/forum/#!forum/redis-db)
* [the `redis` tag at StackOverflow](http://stackoverflow.com/questions/tagged/redis)
* [/r/redis subreddit](http://www.reddit.com/r/redis)
* [the irc channel #redis](http://webchat.freenode.net/?channels=redis) on freenode
