### ISSUE TITLE
ZREVRANK: documentation is confusing.

### ISSUE THREAD

**Issue by bharathalapati23** [redis/redis-doc#2354]
WITHSCORE is documented in ZREVRANK saying it is available from 7.2.0 but the latest stable version is 7.0.9. Also the examples are showing an error for WITHSCORE argument, most probably for the same reason. 

This is a little bit confusing. Adding the latest stable version to history could solve this.

Would love to take this up. Let me know how to contribute as I'm not able to find history section in the codebase

**Comment by enjoy-binbin** [comment]
Hi, this is expected. btw, Redis 7.2 RC1 will be release in the next week.

i think the history part has nothing to do with the stable version,
we should only need to care about the stuff inside the version.
btw, the history part code is stored in the redis code.
you think remove the WITHSCORE and the 7.2 from history will help?

**Comment by bharathalapati23** [comment]
I think removing the WITHSCORE will definitely cause less confusion. But adding the current stable version to an FYI in history section would make way more sense in my opinion

**Comment by enjoy-binbin** [comment]
get it. sadly, i think currently we won't remove the WITHSCORE.

@itamarhaber can you give some advices?

**Comment by bharathalapati23** [comment]
Hey I would love to do the incorporation of this latest build into the docs. Would love to take this up. Let me know how I could contribute here

**Comment by oranagra** [comment]
i'm not certain i follow.
you wanna automatically show a bold hint in the "history" (and "since") section next to any line that mentions a version that's not released yet?
that sounds nice.

p.s. i don't think you can afford to run the interactive examples against the released version, it'll mean we can't merge docs PRs of new commands that are not released yet.
maybe we'll need to add some exception in some way...

**Comment by SoulPancake** [comment]
@oranagra Can you or someone suggest how the response for ZREVRANK WITHSCORE or ZRANK WITHSCORE must look like?
Need it for a separate implementation

**Comment by itamarhaber** [comment]
Hello @SoulPancake 

Here you go:

```
127.0.0.1:6379> ZADD zset 1 a 2 b 3 c
(integer) 3
127.0.0.1:6379> ZRANK zset b WITHSCORE
1) (integer) 1
2) "2"
127.0.0.1:6379> HELLO 3
1# "server" => "redis"
2# "version" => "255.255.255"
3# "proto" => (integer) 3
4# "id" => (integer) 4
5# "mode" => "standalone"
6# "role" => "master"
7# "modules" => (empty array)
127.0.0.1:6379> ZRANK zset b WITHSCORE
1) (integer) 1
2) (double) 2
```

Mind you, you can run Redis 7.2-rc1 and check it out locally :)
