### ISSUE TITLE
There is an issue in Who's using Redis? tab

### ISSUE THREAD

**Issue by AyushForceBolt219** [redis/redis-doc#2376]
When I have clicked to Twitter in leads me to the [https://www.infoq.com/presentations/Real-Time-Delivery-Twitter/](url) instead of twitter main website and snapchat link leads me to the twitter website interesting isn't it and craigslist leads me to the bolg page
![image](https://user-images.githubusercontent.com/102041172/229061148-bc6eac76-f1db-44ad-904d-3bd7fb00938a.png)
as you can see bottom left corner link and my cursor hovering onto the snapchat.

**Comment by SamsonLamichhane** [comment]
I've changed  companies URL on https://github.com/redis/redis-doc/pull/2432/commits/4725e3026feb59a24574c0dc187a562935ae7db6

**Comment by mich-elle-luna** [comment]
This page links to article that describe how each company is using Redis, so I believe it is as-designed content. Closing.
