### ISSUE TITLE
Redis Pub/Sub

### ISSUE THREAD

**Issue by Artemoire** [redis/redis-doc#2378]
Docs are not transparent regarding message delivery guarantees, is it at-most-once, at-least-once etc.

Also, not clear on the order of delivery, do subscribers receive messages in order of publish ?

**Comment by itamarhaber** [comment]
Hello @Artemoire - thanks for pointing this out.

I've tried making things more [transparent](https://github.com/redis/redis-doc/pull/2379/files#diff-467eea02938652e4b714620639126cf28168a2ab906f013613940b5097300fb1R41-R49) and [clearer](https://github.com/redis/redis-doc/pull/2379/files#diff-467eea02938652e4b714620639126cf28168a2ab906f013613940b5097300fb1R23) via [#2379](https://github.com/redis/redis-doc/pull/2379) - please feel free to contribute :)
