### ISSUE TITLE
Client-side caching in Redis - which .NET clients support this?

### ISSUE THREAD

**Issue by Pikabanga** [redis/redis-doc#2387]
Hi!

I'm trying to figure out which .NET clients support client-side caching like described in this article: https://redis.io/docs/manual/client-side-caching/

Does for example StackExchange.Redis support it? https://github.com/StackExchange/StackExchange.Redis

**Comment by itamarhaber** [comment]
Hello @Pikabanga 

I found this open issue in StackExchange.Redis' repo: https://github.com/StackExchange/StackExchange.Redis/issues/1461
