### ISSUE TITLE
Scaling with Redis Cluster

### ISSUE THREAD

**Issue by Himachallad** [redis/redis-doc#2399]
We have a description of how to start scaling using `create-cluster` script in Redis. `make` step is not mentioned here.

**Comment by itamarhaber** [comment]
Hello @Himachallad 

Thanks for reporting this, but I don't think this is a real issue.
We also don't instruct people to clone the repository, or `make` to run redis-cli.
These IMO, are not in the scope of this doc.

**Comment by Himachallad** [comment]
Thanks, @itamarhaber 
I personally feel that cloning a repository is implicit, but running `make` command in the setup is not very common. Although, if you believe this is out of scope,  I will close this ticket.
