### ISSUE TITLE
Python guide: No background-color set on page body

### ISSUE THREAD

**Issue by hemebond** [redis/redis-doc#2404]
The page body element does not have a CSS `background-color` set which means it will use the default browser background colour. This can render the page unreadable, if the browser has a dark background colour, because the CSS *does* set a font colour.

![image](https://user-images.githubusercontent.com/424218/236595804-e5143ae5-f499-4b3e-939b-d5f8c282070f.png)

**Comment by zuiderkwast** [comment]
I believe the design and functionality of the website is in https://github.com/redis/redis-website.

redis-doc is only the content.

**Comment by hemebond** [comment]
Ah, sorry about that. I think I just followed a Github link on the page.

**Comment by zuiderkwast** [comment]
No worries. If you open an issue or PR on the other repo, feel free to post the link to it here and close this issue.

**Comment by itamarhaber** [comment]
I'll look into it shortly.

The website's repo is at https://github.com/redis-stack/redis-stack-website.

**Comment by hemebond** [comment]
@itamarhaber In Firefox _Settings_, under _Language and Appearance_:

![image](https://github.com/redis/redis-doc/assets/424218/149e0abf-3bc2-4bfe-8567-42d0ace11f4e)

**Comment by itamarhaber** [comment]
Thanks @hemebond - the "experience" is indeed reproducible w/ FF when I switch the default text and background colors.

I've deployed the fixes (https://github.com/redis-stack/redis-stack-website/pull/105 && https://github.com/redis-stack/redis-stack-website/pull/106) - please ack.

**Comment by hemebond** [comment]
@itamarhaber Very readable now. Thank you.
