### ISSUE TITLE
Clarity on Lua replicate_commands

### ISSUE THREAD

**Issue by cnrmrphy** [redis/redis-doc#2412]
Should [this line](https://github.com/redis/redis-doc/blob/7f52d5cc22e273af909773c783b6d5eed2ee56ee/docs/manual/programmability/eval-intro.md?plain=1#L284) in the docs say "... it will *not* always succeed?"

> This function is deprecated as of Redis 7.0, and while you can still call it, it will always succeed.

**Comment by enjoy-binbin** [comment]
it will always succeed. Now it will always replicate commands. We removed the other option

**Comment by itamarhaber** [comment]
Closing as answered.
