### ISSUE TITLE
Query regarding shortcode blocks

### ISSUE THREAD

**Issue by SoulPancake** [redis/redis-doc#2417]
What is the source for shortcodes like this within the markdown files
https://github.com/redis/redis-doc/blob/284dc0af0fe8b6a3518e4313fa5c7677aca9b648/commands/set.md?plain=1#L43

Asking because I'm interested in contributing to Code examples in the documentations like the following and citing the source for go-redis or rueidis ( in Golang )
![image](https://github.com/redis/redis-doc/assets/70265851/f56345b1-e2c6-49b2-83b3-a41a040853f2)

**Comment by uglide** [comment]
Hey @SoulPancake 
Thanks for your interest in contributing the code examples. You can find the instruction here https://github.com/redis-stack/redis-stack-website#how-to-add-a-multi-language-code-example-to-redisio
@elena-kolevska is currently working on adding Go-Redis code examples, so please reach her out in this PR https://github.com/redis/go-redis/pull/2601
