### ISSUE TITLE
Scaling with Redis Cluster

### ISSUE THREAD

**Issue by jiangyunpeng** [redis/redis-doc#2427]
hello 

I wanted to talk about the 《Remove a node 》sections [in this chapter](https://redis.io/docs/management/scaling/#remove-a-node) , recently i prepared to remove some failed node in cluster ,when i used redis-cli  --cluster del-node 10.20.32.2:6383 44a0355dff74211554c4df6a7daaca5d2cde1227 i got error: " Could not connect to Redis at failed-node-ip:failed-node-port: Connection refused ". 

The document did not note how to delete failed node . actually it should use redis-cli  --cluster call 10.20.32.3:6380 cluster forget 808bd1a6208b833f005305113fe5d9d5102ede96   i thought cluster forget command must to be applied on every node ( if i was wrong welcome to correct me)

i've spend a few time to find the correct way to remove failed node , so i hope redis-doc will add it , thank you

**Comment by jiangyunpeng** [comment]
hello @itamarhaber  there is my PR https://github.com/redis/redis-doc/pull/2434   thanks

**Comment by zuiderkwast** [comment]
Closed by #2434
