### ISSUE TITLE
sendCommand() method about the use

### ISSUE THREAD

**Issue by RssInteractive** [redis/redis-doc#2429]
in this library

The sendCommand() method and the existing methods such as HGET, HSET seem to be no different.

I want to send a raw format command, but the parameters are not appropriate error every time.

The command I want to send is:

await redis.sendCommand("HSET myKey name Emrah age 29 job Eng");

I want to send a command like this.

how can I do?

Thanks.

**Comment by itamarhaber** [comment]
Hello @RssInteractive 

It appears that your question is about a client, so you'd be able to get better replies to your question at that client's repository.

In any case, it looks like you're using a JavaScript client. As far as I know, you should use the `sendCommand` method as follows:

```
await redis.sendCommand("HSET", "myKey", "name ", "Emrah", "age", 29, "job", "Eng");
```

**Comment by RssInteractive** [comment]
Hello,

My goal was to save all field and value values ​​in an object with a single redis command.

I solved my problem. I tried the method you showed before, but it gave an error in the number of arguments. 

**Problem solution:**

**let object = {
 id : 1,
 name: "test"
}**
**await redis.HSET(key,object)**

Thanks for your reply, we can close the issue.
