### ISSUE TITLE
Redis benchmark options are outdated

### ISSUE THREAD

**Issue by SamsonLamichhane** [redis/redis-doc#2431]
The [options supported document ](https://redis.io/docs/management/optimization/benchmarks/) is missing a lot of useful options to efficiently use Redis benchmark. Example, --user --cluster etc

**Comment by SamsonLamichhane** [comment]
Add all options on https://github.com/redis/redis-doc/pull/2432/commits/5e96fad09effedbc825cdea0154fceffd2c215e3

**Comment by mich-elle-luna** [comment]
closing as this was never reviewed
