### ISSUE TITLE
"sentinels" and "slaves" in redis sentinel info never decrease

### ISSUE THREAD

**Issue by ly161110323** [redis/redis-doc#2433]
A redis cluster with one master node and two replica nodes. There are three sentinels to monitor the master node. 
sentinel config is follow:
`protected-mode no
bind 0.0.0.0
port 26380
daemonize yes
appendonly yes
pidfile "/var/run/sentinel.pid"
logfile "/data/log/redis/sentinel.log"

dir "/data"
sentinel deny-scripts-reconfig yes
sentinel monitor local-master *.*.*.* 16379 2

sentinel down-after-milliseconds local-master 3000
sentinel auth-pass local-master ***`

when the sentinels start one by one, "slaves" normally increases to 3.
`127.0.0.1:26380> info sentinel
# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_tilt_since_seconds:-1
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
sentinel_simulate_failure_flags:0
master0:name=local-master,status=ok,address=*.*.*.*:16379,slaves=2,sentinels=3`

When I shutdown one sentinels, "+sdown sentinel" in sentinel log shows that this action. However, the "slaves" doesn't decrease, it remains at 3. 
![image](https://github.com/redis/redis-doc/assets/42904516/90e73522-0c8e-474f-9544-96e6610c3ccb)

 It's same for shutting down replica node. Why? Could anyone help me find the problem?

**Comment by moticless** [comment]
Hi @ly161110323,
Once a new sentinel is being "seen" by other sentinels, it is recorded in their databases. 
Later on, the command `info sentinel` will return the number of recorded `sentinels`, irrelated to their availability.

**Comment by ly161110323** [comment]
> Hi @ly161110323, Once a new sentinel is being "seen" by other sentinels, it is recorded in their databases. Later on, the command `info sentinel` will return the number of recorded `sentinels`, irrelated to their availability.

Thanks for your answer! Another question is that it's same for `master` and `slave`. When I `kill` the `master`, sentinels successfully vote new `master`. Currently there are one `master` and one `slave`, but the command `info sentinel` shows that `slaves=2`. Is it right? The `sentinel` log shows that `+sdown slave...`, which means that `slave` subjective down.

**Comment by mich-elle-luna** [comment]
not a doc issue, but questions. Pleas ask on our Redis discord server if you need help.
