### ISSUE TITLE
Redis swap documentation + possible issue with Redis.

### ISSUE THREAD

**Issue by Yossifsolman** [redis/redis-doc#2437]
Hello, how are you guys?

**I have small machine on Google Cloud (E2 1GB RAM 2vCPU)**

I have deployment of litespeed-wordpress:
https://docs.litespeedtech.com/cloud/images/wordpress/

My machine don't have a swap file, and i set in the kernel (/etc/sysctl.conf):
`vm.swappiness=0`

Now i experience a lot of overload, i don't see it when i run "htop" on the SSH,
But in the overload time, when i restart redis with "systemctl"
I see the overload go down drastically (Redis can be a PHP process as well).

I suspect it's maybe a swap issue or RDB.

------

**Now, i looked on the Redis doc's before a week ago and i see Redis put the swap recommendation as ¨deprecated":**
https://redis.io/docs/reference/internals/internals-vm/

**In the same time, i look on Redis Enterprise actually recommended turning off the swap file complete (like my machine):**
https://docs.redis.com/latest/rs/installing-upgrading/configuring/linux-swap/
**I use UBUNTU, but i believe it's the same as Linux.**

**Couple of questions:**
1. Redis still try to swap? Even if you don't have a swap file and sysctl.conf set vm.swappiness to 0?
2. What is actually recommended now after you declare Virtual Memory (swap) as deprecated? (It's ok without swap file?)
3. My memory is already on 80% – 85% (1GB RAM in total), should i configure Redis.conf with maxmemory 100mb? 
4. Should i disable the RDB snapshot in my case?

**I tried to keep the default configuration… but i am afraid it's not possible with this deployment and the type of the machine.**

Be happy for your advice, guys.

**Comment by mich-elle-luna** [comment]
Please ask for help on our Redis Discord server if you still have a question.
