### ISSUE TITLE
SCAN command in redis cluster picks nodes in random 

### ISSUE THREAD

**Issue by KrishnaPravin** [redis/redis-doc#2440]
Steps to reproduce:
1. `redis-cli -c -h <redis-host-in-cluster-mode>`
2. `scan 0 match * count 500`

This runs the SCAN command on a random node in the cluster and the node information is also not returned in the result.

Can this scenario be mentioned in the documentation.

**Comment by itamarhaber** [comment]
Discussion: redis/redis#12314

**Comment by mich-elle-luna** [comment]
based on linked issue, closing this doc issue, please re-open if I misunderstand
