### ISSUE TITLE
Redis configuration file example

### ISSUE THREAD

**Issue by talsh5528** [redis/redis-doc#2451]
I found the option to use the SNI flag on the command redis-cli, how can I configure sni as part of my replication configuration?

after reading your doc, I found out that I can use cluster-announce-hostname, but when I try to configure that I get an error.
`(error) ERR Unsupported CONFIG parameter: cluster-announce-hostname`

**Comment by mich-elle-luna** [comment]
Please ask your question on our Redis Discord server if you still find this issue.
