### ISSUE TITLE
Do you have documentation? 

### ISSUE THREAD

**Issue by DenisLutsky** [redis/redis-doc#2461]
https://redis.io/docs is this a valid website or is this just a mock? because any page Im trying to open returns 404

**Comment by dmaier-redislabs** [comment]
Hi Denis,

I can't reproduce this right now.

The links you are referring to should be

```
<nav>   
            <a href="/docs/about/">Introduction to Redis</a>
            <p>Learn about the Redis open source project</p>
          
            <a href="/docs/getting-started/">Get started with Redis</a>
            <p>How to get up and running with Redis</p>
          
            <a href="/docs/ui/">User interfaces</a>
            <p>Learn how to use Redis interfaces</p>
          
            <a href="/docs/data-types/">Redis data types</a>
            <p>Overview of data types supported by Redis</p>
          
            <a href="/docs/interact/">Interact with data in Redis</a>
            <p>How to interact with data in Redis, including searching, querying, triggered functions, transactions, and pub/sub.</p>
          
            <a href="/docs/clients/">Get started using Redis clients</a>
            <p>Get started using Redis clients. Select your library and connect your application to a Redis database. Then, try an example.</p>
          
            <a href="/docs/manual/">Use Redis</a>
            <p>A developer's guide to Redis</p>
          
            <a href="/docs/management/">Manage Redis</a>
            <p>An administrator's guide to Redis</p>
          
            <a href="/docs/reference/">Redis reference</a>
            <p>Specifications and protocols</p>
        </nav>
```


As far as I can see they are all working. 

* Does the problem still persist for you?
* Which browser are you using?

Regards,
David

**Comment by DenisLutsky** [comment]
> Hi Denis,
> 
> I can't reproduce this right now.
> 
> The links you are referring to should be
> 
> ```
> <nav>   
>             <a href="/docs/about/">Introduction to Redis</a>
>             <p>Learn about the Redis open source project</p>
>           
>             <a href="/docs/getting-started/">Get started with Redis</a>
>             <p>How to get up and running with Redis</p>
>           
>             <a href="/docs/ui/">User interfaces</a>
>             <p>Learn how to use Redis interfaces</p>
>           
>             <a href="/docs/data-types/">Redis data types</a>
>             <p>Overview of data types supported by Redis</p>
>           
>             <a href="/docs/interact/">Interact with data in Redis</a>
>             <p>How to interact with data in Redis, including searching, querying, triggered functions, transactions, and pub/sub.</p>
>           
>             <a href="/docs/clients/">Get started using Redis clients</a>
>             <p>Get started using Redis clients. Select your library and connect your application to a Redis database. Then, try an example.</p>
>           
>             <a href="/docs/manual/">Use Redis</a>
>             <p>A developer's guide to Redis</p>
>           
>             <a href="/docs/management/">Manage Redis</a>
>             <p>An administrator's guide to Redis</p>
>           
>             <a href="/docs/reference/">Redis reference</a>
>             <p>Specifications and protocols</p>
>         </nav>
> ```
> 
> As far as I can see they are all working.
> 
> * Does the problem still persist for you?
> * Which browser are you using?
> 
> Regards, David

Hi, still have no response.
Im using Chrome Version 114.0.5735.199 (Official Build) (64-bit), Windows 11 Pro version 22H2 build 22621.1928

I asked my friends to check, and it wont work for them too.

https://redis.io/docs/stack/get-started/install/docker/
https://redis.io/docs/interact/search-and-query/reference/vectors

**Comment by dmaier-redislabs** [comment]
Hi Denis,

we fixed some redirects and I tried every link that can be found on https://redis.io/docs and it worked.

- https://redis.io/docs/stack/get-started/install/docker/ should now be redirected to https://redis.io/docs/getting-started/install-stack/docker/
- https://redis.io/docs/stack/search/reference/vectors is now under https://redis.io/docs/interact/search-and-query/search/vectors/

Both URL should be automatically redirected.

Where did you get the https://redis.io/docs/interact/search-and-query/reference/vectors from? It was never supposed to exist, but it could well be that we missed a relative link.

Regards,
David

**Comment by DenisLutsky** [comment]
I get these links from your website, but I don't remember from which page, so I can't find them.
That's why asked if that website is mock or a real documentation.

PS Sorry, for the first comment in this passive-aggressive form, I was very tired at this moment, and links in documentation didn't work

**Comment by DenisLutsky** [comment]
Thanks
