### ISSUE TITLE
Link is broken on page https://redis.io/commands/scan/

### ISSUE THREAD

**Issue by cdwheatley** [redis/redis-doc#2462]
The link to [The Redis Keyspace](https://redis.io/docs/manual/the-redis-keyspace.md) the on the page https://redis.io/commands/scan/ is broken.

**Comment by ashrude** [comment]
I believe that was introduced with this commit #2419

**Comment by elena-kolevska** [comment]
Thanks for catching this @cdwheatley . We'll be adding the proper alias today. In the meantime, here's the new location of the keyspace tutorial: https://redis.io/docs/manual/keyspace/

**Comment by dmaier-redislabs** [comment]
We added an alias to https://redis.io/docs/manual/the-redis-keyspace and fixed the link on the SCAN page. This should be fixed now.
