### ISSUE TITLE
404 on redisearch quick_start link

### ISSUE THREAD

**Issue by LaVolsi** [redis/redis-doc#2463]
https://redis.io/docs/interact/search-and-query/quick_start

is a 404 now. I need to see the guide to install redisearch

**Comment by dmaier-redislabs** [comment]
Hi LaVolsi,

the correct URL is https://redis.io/docs/interact/search-and-query/quickstart/ .

Regards,
David

**Comment by dmaier-redislabs** [comment]
@elena-kolevska Let us add an alias to https://redis.io/docs/interact/search-and-query/quick_start, too.

**Comment by dmaier-redislabs** [comment]
This should be fixed now.
