### ISSUE TITLE
Error 404: Page Not Found.

### ISSUE THREAD

**Issue by AmkaE** [redis/redis-doc#2464]
While I was trying to access this link (https://redis.io/docs/clients/stack-node/) provided by the docs under "https://redis.io/docs/clients/", I encountered 404 error.  Also these following links are not working [ "https://redis.io/docs/clients/stack-dotnet/ ", "https://redis.io/docs/clients/stack-python/ ", "https://redis.io/docs/clients/stack-spring/" ], The all result in 404 error.

**Comment by elena-kolevska** [comment]
Thanks for reporting @AmkaE . We're fixing this today. In the meantime, here are the correct links:

[Redis OM .NET](https://redis.io/docs/clients/om-clients/stack-dotnet/)
[Redis OM Spring](https://redis.io/docs/clients/om-clients/stack-spring/)
[Redis OM Node.js](https://redis.io/docs/clients/om-clients/stack-node/)
[Redis OM Python](https://redis.io/docs/clients/om-clients/stack-python/)

**Comment by dmaier-redislabs** [comment]
This should be fixed now.
