### ISSUE TITLE
RedisGraph End-of-Life Announcement , redis-stack-server startup service error

### ISSUE THREAD

**Issue by JamesMonges** [redis/redis-doc#2470]
RedisGraph End-of-Life Announcement, redis-stack-server startup service error.
error content:Module /usr/local/Caskroom/redis-stack-server/6.2.6-v7/lib/redistimeseries.so failed to load: dlopen(/usr/local/Caskroom/redis-stack-server/6.2.6-v7/lib/redistimeseries.so, 0x0006): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: <30A14AFA-B380-3E51-A8D2-B72E74AAE7F7> /usr/local/Caskroom/redis-stack-server/6.2.6-v7/lib/redistimeseries.so
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file, not in dyld cache)
18886:M 06 Jul 2023 15:49:46.029 # Can't load module from /usr/local/Caskroom/redis-stack-server/6.2.6-v7/lib/redistimeseries.so: server aborting

**Comment by dmaier-redislabs** [comment]
Hi James,

could you please give us a bit more background details about which issue you are facing? It seems you are missing a shared library, but I am not sure how this is associated to the Graph EOL announcement or documentation.

Regards,
David

**Comment by mich-elle-luna** [comment]
closing as stale, please open a new issue if you still have this issue or ask on our Redis Discord server.
