### ISSUE TITLE
Streams tutorial is missing

### ISSUE THREAD

**Issue by johnmreynolds** [redis/redis-doc#2472]
The first result when searching the redis site for 'streams' is 

https://redis.io/docs/data-types/streams-tutorial/

Which is also found in many Google searches about streams.

But this URL returns 404.

**Comment by elena-kolevska** [comment]
Thanks for reporting @johnmreynolds . The content of that page was moved to [https://redis.io/docs/data-types/streams/](https://redis.io/docs/data-types/streams/).
We'll be adding the redirect today.

**Comment by elena-kolevska** [comment]
This is now fixed
