### ISSUE TITLE
Redis CLI - Missing Information in "String quoting and escaping"

### ISSUE THREAD

**Issue by Marriam-Naeem** [redis/redis-doc#2505]
Page to be edited: https://github.com/redis/redis-doc/edit/master/docs/ui/cli.md

Redis server v=7.0.12

I encountered an issue while following the Redis documentation, specifically in the section titled "String Quoting and Escaping." Here, with the escape sequence, it is not mentioned that the decoded output with escape characters is displayed on the CLI only when Redis-cli is opened using `--raw`. This is a major issue and may mislead some readers. If we follow what's mentioned in the documentation the output is displayed like this:

```
$ redis-cli
127.0.0.1:6379> SET mykey "Hello\nWorld"
OK
127.0.0.1:6379> GET mykey
Hello\nWorld
```
However, the correct way of obtaining the human-readable output with escape characters is:

```
$ redis-cli --raw
127.0.0.1:6379> SET mykey "Hello\nWorld"
OK
127.0.0.1:6379> GET mykey
Hello
World
```

**Comment by mich-elle-luna** [comment]
--raw is documented on this same page in the section just prior to string quoting and escaping, titled command line usage. Closing as complete.
