### ISSUE TITLE
Redis Stack Tutorial is gone

### ISSUE THREAD

**Issue by Lanznx** [redis/redis-doc#2508]
https://redis.io/docs/stack/get-started/tutorials/

![截圖 2023-08-08 下午3 23 01](https://github.com/redis/redis-doc/assets/96360357/98391c40-7737-47fc-bd4e-8b0a6f9e1dec)

**Comment by itamarhaber** [comment]
Hello @Lanznx 

Thank you for reporting this. Can you also tell us how you got to that url?

**Comment by dwdougherty** [comment]
@Lanznx I've fixed this broken link with a PR to a related repo:

https://github.com/redis-stack/redis-stack-website/pull/120

I'll circle back when it's merged.
