### ISSUE TITLE
`SCAN` command page doesn't explain what `COUNT` does or how `MATCH` works sufficiently.

### ISSUE THREAD

**Issue by simonprickett** [redis/redis-doc#2529]
The `SCAN` command page doesn't explain how the `COUNT` modifier works - necessary as this is confusing because it's not exactly a guarantee of how many elements the scan family of commands return... nor how `MATCH` works.  It also does not do a good job of explaining how the cursor works and when to know you have completed a scan of the keyspace.

**Comment by BhavyaCodes** [comment]
Yes please, as a beginner to redis, I kept thinking I must be doing something wrong as I would always get more than the `COUNT` value when using `SSCAN` command until someone explained it to me how it works. I think the docs should make it more clear

**Comment by zuiderkwast** [comment]
The SCAN command page contains this:

> For more information on SCAN please refer to the [The Redis Keyspace](https://redis.io/docs/manual/keyspace) tutorial.

On this tutorial page, it is clear what COUNT, MATCH, the cursor and the guarantees are. Do you agree?

I think it would be much better to move this information to the SCAN command page and instead link from the tutorial to the command page, like "for more information, see the SCAN command". IMO the parameters to a command and the return value need to be documented on that command's page.

I would accept a PR moving the relevant information to the command's page. @itamarhaber would you agree?

**Comment by simonprickett** [comment]
Makes sense to me... other command pages refer to the `SCAN` page for an explanation of the scan mechanics:

* https://redis.io/commands/sscan/
* https://redis.io/commands/hscan/

so the `SCAN` page should fully describe all of the options to the command on the command's page as these should be one stop shop pages.

I think this used to be the case, in which case the `SCAN` page seems to have gone backwards in usefulness.

**Comment by zuiderkwast** [comment]
Have you found the commit where this was changed? There was new design and new backend of the website in which in a few cases some usefulness got lost. I'm sure whoever did this didn't know the full picture. Let's restore the usefulness.

**Comment by simonprickett** [comment]
> Have you found the commit where this was changed? There was new design and new backend of the website in which in a few cases some usefulness got lost. I'm sure whoever did this didn't know the full picture. Let's restore the usefulness.

Here I think 882c184514f88f048df3d773e300a39882773e9d

**Comment by zuiderkwast** [comment]
Sorry, didn't mean to close it.

#2419 is a huge change. Among other tutorials, it adds the Keyspace page which is good to have, but the details of SCAN's arguments need to be on the SCAN command page. @elena-kolevska Are you OK with moving some command details back to SCAN and keeping an overview such as SCAN vs KEYS on the Keyspace page?

**Comment by simonprickett** [comment]
@zuiderkwast Elena is no longer with Redis so probably isn't the decision maker here.

**Comment by zuiderkwast** [comment]
@simonprickett OK, let's just change it then. Do you want to make a PR?

**Comment by simonprickett** [comment]
> @simonprickett OK, let's just change it then. Do you want to make a PR?

Sounds good - want to assign this to me?
