### ISSUE TITLE
Command Does Not Include Response Type

### ISSUE THREAD

**Issue by skeggse** [redis/redis-doc#253]
`commands.json` should include an expected response type for each command. For example, `INCR` should have a `response` property of `"integer"`, because under normal operating conditions it [responds with a long integer](http://redis.io/commands/incr).

**Comment by itamarhaber** [comment]
Hello @skeggse 

I'm not sure that I understand the issue -  commands.json at its current form does not feature the response type as it is already specified in each command's .md file.

**Comment by skeggse** [comment]
I opened this six years ago, and have no recollection about the problem I was trying to solve or any additional details. I'll consider this closed.

**Comment by itamarhaber** [comment]
Sure - my apologies for the belated reply.

**Comment by nl-brett-stime** [comment]
@itamarhaber, if I recall correctly, my use case was having response types in the JSON so that machines could process them. Specifically, there was a TypeScript library that derived typings from this project so that types could be verified via static analysis at compile time.

**Comment by itamarhaber** [comment]
@nl-brett-stime  === @skeggse ?

Ok, I can see how this could be handy for clients that want to know beforehand about the response's type. Funnily enough, with RESP3 this should be a moot point. Still, it may be worth the effort if only for completeness' sake.

**Comment by itamarhaber** [comment]
Reopening this for further consideration

**Comment by skeggse** [comment]
Yeah this seems reasonable.

>@nl-brett-stime === @skeggse ?

Nope!

**Comment by nermiller** [comment]
Closing as stale.
