### ISSUE TITLE
Redis Cluster hard to find in menu

### ISSUE THREAD

**Issue by zuiderkwast** [redis/redis-doc#2533]
You need to know that "Scaling" is what you need to look for to find the cluster spec. It's true that cluster can scale but it wasn't obvious to me that these pages are hidden under Scaling.

Can we expand the menu item to "Scaling with Redis Cluster"? @elena-kolevska @itamarhaber

**Comment by dwdougherty** [comment]
Opened doc ticket DOC-2711.

**Comment by dwdougherty** [comment]
There's nothing wrong with this issue and I fully intend to make the requested fix. Adding references to internal JIRAs in an old habit of mine, and not really relevant to open source docs. I'll refrain from doing so in the future. Thank you for calling this out!

**Comment by zuiderkwast** [comment]
Hehe no worries. It's just hard for us outsiders to know what's in that JIRA ticket anyway (and I fail to see it's purpose, but I guess there is one). :-)
