### ISSUE TITLE
When using REDIS SET with both KEEPTTL and an actual TTL what happens

### ISSUE THREAD

**Issue by EfratMalkaMS** [redis/redis-doc#2534]
Hi,

I'm trying to figure out what takes precedence when using REDIS SET with both KEEPTTL and an actual TTL. Will the specified TTL be used or alternatively the existing TTL is kept?
Thanks,
Efrat

**Comment by enjoy-binbin** [comment]
that will be a `syntax error` since they are incompatible:
```
127.0.0.1:6379> set key value ex 1000 keepttl
(error) ERR syntax error
```

there is a web client you can try: https://redis.io/
