### ISSUE TITLE
redis describe docs is not enough strict? 

### ISSUE THREAD

**Issue by pipipapi** [redis/redis-doc#2536]
https://redis.io/docs/management/optimization/memory-optimization/ 
on this page : 
      **When Redis is compiled as a 32-bit target, it uses a lot less memory per key, since pointers are small, but such an instance will be limited to 4 GB of maximum memory usage. To compile Redis as 32-bit binary use make 32bit . RDB and AOF files are compatible between 32-bit and 64-bit instances (and between little and big endian of course) so you can switch from 32 to 64-bit, or the contrary, without _problems.**_

that means 32bit compatible with 64bit mutual, that's not at all, since "long 
 or double's"  precision will be lost if change to 32bit.  isn't it ?

**Comment by oranagra** [comment]
the values for keys are using `long long` and `double`, both are 8 bytes even on 32bit machines / builds.
it's just that the pointers and some `long` indexes are 32bit instead of 64bit, and thus some structs are smaller.
i don't see any problem with the documentation.
