### ISSUE TITLE
Default Mechanism of Expiration/Deletion of entries in stream

### ISSUE THREAD

**Issue by mangesh2806** [redis/redis-doc#2539]
Hi ,

I have started to use redis streams as it is in memory data and append data structure, i will creating one stream key and will append the entries to it. I want to know how many entries i can add it to single key and also what is default mechanism of expiration or deletation of entries.

**Comment by mangesh2806** [comment]
It not document anywhere, please let me know if you have any reference for the same.

**Comment by mich-elle-luna** [comment]
https://redis.io/docs/data-types/streams/ Since the sequence number is 64 bit wide, in practical terms there is no limit to the number of entries that can be generated within the same millisecond. Use XDEL to delete to delete items by ID.
