### ISSUE TITLE
ACL rules - `+@slow +@fast` instead of `+@all`?

### ISSUE THREAD

**Issue by JeffreyCA** [redis/redis-doc#2556]
Regarding this paragraph from the ACL documentation [here](https://redis.io/docs/management/security/acl/#command-categories):

> If you say `+@all`, all the commands can be executed by the user, even future commands loaded via the modules system. However if you use the ACL rule `+@read` or any other, the modules commands are always excluded.

Is it fair to say that we can simply substitute `+@slow +@fast` for `+@all` if we want the same effect as `+@all` without potential module commands being included (since every command is either `@slow` or `@fast`)?

**Comment by dwdougherty** [comment]
Hi Jeffrey. I will need to have a more technical person weigh in here, so I've labeled this issue as such.

**Comment by JeffreyCA** [comment]
@itamarhaber Thanks for explaining. I'm sorry I meant to say `@slow` and `@fast`:

> fast - Fast O(1) commands. May loop on the number of arguments, but not the number of elements in the key.

> slow - All commands that are not fast.

I suppose the answer still remains the same?

**Comment by itamarhaber** [comment]
@JeffreyCA Aye, more or less (excluding modules, all commands are one or the other in this case).

Is this purely a philosophical discussion, or is there a specific challenge/goal that you're up against?

**Comment by JeffreyCA** [comment]
It was more of a philosophical question, thanks for answering 🙂
