### ISSUE TITLE
Get started with Redis

### ISSUE THREAD

**Issue by zhouhonglin520** [redis/redis-doc#2562]
redis 6.2 version, master-slave mode, when the slave node is greater than 4, there will be a CPU surge, what is the cause of this?

My contact information can be 873196868@qq.com

**Comment by mich-elle-luna** [comment]
Please ask your question on our Redis Discord server if you still need help. Closing as not a doc issue.

**Comment by zhouhonglin520** [comment]
Please give me the address of the Redis Discord server




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redis/redis-doc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月27日(星期三) 上午7:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redis/redis-doc] Get started with Redis (Issue #2562)





 
Please ask your question on our Redis Discord server if you still need help. Closing as not a doc issue.
