### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by Didas-git** [redis/redis-doc#2563]
The [`SMEMBERS`](https://redis.io/commands/smembers/) page shows all the examples as `failed to fetch`
![image](https://github.com/redis/redis-doc/assets/80978939/8ee87adf-ee23-4b45-afb9-aa89951da078)

**Comment by dwdougherty** [comment]
Thank you for reporting this!

**Comment by dwdougherty** [comment]
Issue fixed (thank you @itamarhaber).

**Comment by Didas-git** [comment]
An update on the issue:
Seems like its not only on `SMEMBERS`, its every page that uses `form class="redis-cli"` (even the main page redis.io)

**Comment by Didas-git** [comment]
This might help
![image](https://github.com/redis/redis-doc/assets/80978939/642f5b49-acfd-4248-9579-a06df740cc9a)

**Comment by itamarhaber** [comment]
Thanks all - this issue has been resolved (with a server restart :)).
