### ISSUE TITLE
The Redis lists documentation does not correspond to the provided example

### ISSUE THREAD

**Issue by Aden-Q** [redis/redis-doc#2566]
Page link: https://redis.io/docs/data-types/lists/

This is the given example for Redis-cli:
```
> RPUSH bikes:repairs bike:1 bike:2
(integer) 5
> BRPOP bikes:repairs 1
1) "bikes:repairs"
2) "bike:2"
> BRPOP bikes:repairs 1
1) "bikes:repairs"
2) "bike:1"
> BRPOP bikes:repairs 1
(nil)
(2.01s)
```
And the doc says:
> It means: "wait for elements in the list **tasks**, but return if after 5 seconds no element is available".

There is no list named 'tasks' in the given context, and the blocking call timeout in the provided example is 1 second, not 5 seconds.

**Comment by dwdougherty** [comment]
Thank you for reporting this! A fix is on the way.
