### ISSUE TITLE
Install Redis on Windows

### ISSUE THREAD

**Issue by hamdand** [redis/redis-doc#2567]
this solution works good on my local machine, but it works only when wsl terminal is running, and it doesn't auto start on my machine, in other wods if im restarting my machine i have to re-run the terminal and start the Redis service again.

**Comment by dwdougherty** [comment]
Hello. Thank you for reaching out.

Installation on Windows is not officially supported at this time, so it's not likely that we'll provide further documentation on Windows-related topics; not saying we won't either. :) That said, I did find [this resource](https://gist.github.com/cromat/a065136db5bdc40f21dc139567ad0340), which looks like it might give you some ideas on how to automate this on your system(s).
