### ISSUE TITLE
High availability with Redis Sentinel

### ISSUE THREAD

**Issue by FischerKim** [redis/redis-doc#2568]
I've setup Sentinel.conf like below:
Node1:
sentinel announce-ip 192.168.111.123
sentinel announce-port 26379
sentinel monitor mymaster 192.168.111.123 6379 1
sentinel down-after-milliseconds mymaster 3000
sentinel failover-timeout mymaster 7000
sentinel parallel-syncs mymaster 1
Node2:
sentinel announce-ip 192.168.111.124
sentinel announce-port 26379
sentinel monitor mymaster 192.168.111.123 6379 1
sentinel down-after-milliseconds mymaster 3000
sentinel failover-timeout mymaster 7000
sentinel parallel-syncs mymaster 1
Node3:
sentinel announce-ip 192.168.111.125
sentinel announce-port 26379
sentinel monitor mymaster 192.168.111.123 6379 1
sentinel down-after-milliseconds mymaster 3000
sentinel failover-timeout mymaster 7000
sentinel parallel-syncs mymaster 1

when commanding 'sentinel master mymaster' on redis-cli -p 26379, it says master is disconnected:
10) "s_down,o_down,master,disconnected"

**Comment by mich-elle-luna** [comment]
Please ask your question on our Redis Discord server if you still need help. Closing as not a docs issue.
