### ISSUE TITLE
Broken links from intall redis documentation page

### ISSUE THREAD

**Issue by cnemri** [redis/redis-doc#2575]
The different installation guide links in https://redis.io/docs/install/install-redis/ are broken:
[Install Redis from Source](https://redis.io/docs/install/install-redis-from-source)
[Install Redis on Linux](https://redis.io/docs/install/install-redis-on-linux)
[Install Redis on macOS](https://redis.io/docs/install/install-redis-on-mac-os)
[Install Redis on Windows](https://redis.io/docs/install/install-redis-on-windows)

**Comment by dmaier-redislabs** [comment]
This should be fixed now. The links got updated to point to the right place.
