### ISSUE TITLE
installation guide for linux s not found.

### ISSUE THREAD

**Issue by folong201** [redis/redis-doc#2578]
on the documentation i can't find the documentation on  how ton install redis on linux

**Comment by dmaier-redislabs** [comment]
Hello,

you can find the Redis installation guides here:

- https://redis.io/docs/install/install-redis/

You can either build it from source, or you can install it via the package manager of your choice. 

If you were looking for Redis Stack, then the installation guides are available here:

- https://redis.io/docs/install/install-stack/ 

Regards,
David
