### ISSUE TITLE
Can't redirect to query documentation page from document database page

### ISSUE THREAD

**Issue by jonahcui** [redis/redis-doc#2582]
![CleanShot 2023-10-25 at 18 12 13](https://github.com/redis/redis-doc/assets/101780038/dfe829e9-29c1-491b-920c-5b62502e0796)

When I click the button, there is a 404 page shows up.

**Comment by dwdougherty** [comment]
Thank you for reporting this! A fix is on the way.

**Comment by mich-elle-luna** [comment]
confirmed this link is now fixed
