### ISSUE TITLE
Does the Redis administration setup tips also adviced for Docker deployment?

### ISSUE THREAD

**Issue by jppdpf** [redis/redis-doc#2583]
Hi, I've been reading the documentation to understand how to deploy Redis.

In the  **Redis setup tips** it talks about Linux kernel settings and memory characteristics.
Since the redis docker is a linux image should I consider the above category tips? 
Both for the container and host?

Thank you!

**Comment by mich-elle-luna** [comment]
You could refer to https://redis.io/docs/install/install-stack/docker/ or ask your question/search up answers on our Redis Discord server.
