### ISSUE TITLE
Redis doc for persistence and batching with AOF

### ISSUE THREAD

**Issue by DanielBauman88** [redis/redis-doc#2585]
https://github.com/redis/redis-doc/blob/edcc598b168dc2933b258413db071d670c000b15/docs/management/persistence.md?plain=1#L157C109-L157C230

"Note that the commands are appended to the AOF after a batch of commands from multiple clients or a pipeline are executed"

Does redis ever batch commands on the server side from multiple clients? I can't see when it would from the docs but I am not very experienced with redis.

My understanding from the pipeline docs (https://github.com/redis/redis-doc/blob/edcc598b168dc2933b258413db071d670c000b15/docs/manual/pipelining/index.md) is that a single redis client can batch commands and send them to the server and they will be executed as a batch - but I am not aware of the server doing aggregation of commands sent from multiple clients.

**Comment by mich-elle-luna** [comment]
If you still have this question, please ask on on our Redis Discord server. Closing as not clearly a docs issue.
