### ISSUE TITLE
Redis replication

### ISSUE THREAD

**Issue by stardustman** [redis/redis-doc#2608]
I read the doc about:

> You can try it yourself via telnet. Connect to the Redis port while the server is doing some work and issue the [SYNC](https://redis.io/commands/sync) command. You'll see a bulk transfer and then every command received by the master will be re-issued in the telnet session. Actually [SYNC](https://redis.io/commands/sync) is an old protocol no longer used by newer Redis instances, but is still there for backward compatibility: it does not allow partial resynchronizations, so now [PSYNC](https://redis.io/commands/psync) is used instead.

how to test? can it explain more clear? I use the telnet command on master  port, I didn't see the  every command received by the master will be re-issued in the telnet session. why?

**Comment by mich-elle-luna** [comment]
Please ask your question in our Redis Discord server if you still have this issue. Closing as not a docs issue.
