### ISSUE TITLE
Redis support for hybrid search using dense and sparse vectors

### ISSUE THREAD

**Issue by swamysrivathsan** [redis/redis-doc#2616]
Hello Team - Can you pl clarify if redis supports hybrid vector search using dense and sparse vectors over dot matrix?

Say, if we use sentence transformers it will result in 1x768 dimensional dense vector and splade-cocondenser model will result in 1x30522 dimensional sparse vector. 

I'ld like to know if Redis as capability to perform hybrid vector search using both these vectors. Can you provide any associated reference documents for this?

TIA

**Comment by mich-elle-luna** [comment]
Refer here https://redis.io/docs/interact/search-and-query/query-use-cases/ or ask your question on our Redis Discord server. Closing as not a docs issue.
