### ISSUE TITLE
one page 404

### ISSUE THREAD

**Issue by 578223592** [redis/redis-doc#2652]
由页面 https://docs.redis.com/latest/stack/bloom/ 链接到的页面：https://redis.io/docs/stack/bloom/quick_start/失效了 。

![image](https://github.com/redis/redis-doc/assets/65906820/e23ec322-e7d4-43ca-b0e0-409bdb12f597)

**Comment by dwdougherty** [comment]
Thank you for catching this bug! Much appreciated.
