### ISSUE TITLE
OBJECT ENCODING - needs an update to use listpack?

### ISSUE THREAD

**Issue by srgsanky** [redis/redis-doc#2658]
https://redis.io/commands/object-encoding/ specifies that lists, hashes and sorted sets are represented using ziplist. Since Redis 7 we use listpack based on the release notes (https://github.com/redis/redis/releases/tag/7.0-rc1).

> Replace ziplist with listpack in Hash, List, Zset (https://github.com/redis/redis/pull/8887, https://github.com/redis/redis/pull/9366, https://github.com/redis/redis/pull/9740)

Does this page need an update?

|        | RAW  | INT  | HT   | ZIPMAP | LINKEDLIST | ZIPLIST | INTSET | SKIPLIST | EMBSTR | QUICKLIST | STREAM | LISTPACK |
| ------ | ---- | ---- | ---- | ------ | ---------- | ------- | ------ | -------- | ------ | --------- | ------ | -------- |
| STRING | ✅    | ✅    |      |        |            |         |        |          | ✅      |           |        |          |
| LIST   |      |      |      |        |            |         |        |          |        | ✅         |        | ✅        |
| SET    |      |      | ✅    |        |            |         | ✅      |          |        |           |        | ✅        |
| ZSET   |      |      |      |        |            |         |        | ✅        |        |           |        | ✅        |
| HASH   |      |      | ✅    |        |            |         |        |          |        |           |        | ✅        |
| MODULE | ✅    |      |      |        |            |         |        |          |        |           |        |          |
| STREAM |      |      |      |        |            |         |        |          |        |           | ✅      |          |

I think we started using listpack for list (https://github.com/redis/redis/commit/2168ccc66) and sets (https://github.com/redis/redis/commit/4e472a1a7) from 7.2.

**Comment by enjoy-binbin** [comment]
yes, the page should be update, do you want to update it?

**Comment by srgsanky** [comment]
Sorry, not at the moment. If you or anyone else wants to update it, please go for it.
