### ISSUE TITLE
Legal question about definition of third party and interaction with software.

### ISSUE THREAD

**Issue by danmarsden** [redis/redis-doc#2694]
Hi team, 

Just a question around your new license that would be helpful to clarify if possible?

The new license has a part which states:
"...Making the functionality of the software or modified version available to third parties includes, without limitation, enabling third parties to interact with the functionality of the software or modified version in distributed form or remotely through a computer network..."

Lets say I have a product as a service offering - lets call that "Widget as a service" - behind the scenes I use Redis.

I sell that "widget as a service" to a client "Bob's hardware"

Is Bob a third party? - does use use of the Widget as a service result in him interacting with the functionality of the redis software meaning that I will need to have a commercial license to use it in this manner?

thanks!

**Comment by dwdougherty** [comment]
Hi Dan. Please direct your question to redis_licensing@redis.com. Thank you!
