### ISSUE TITLE
Node.js hSet raises WRONGTYPE error when using keys with hyphens

### ISSUE THREAD

**Issue by Enes-Kayiklik** [redis/redis-doc#2702]
**Problem:**
I'm encountering a WRONGTYPE Operation against a key holding the wrong kind of value error when using hSet with keys containing hyphens (-). The error occurs only when hyphens are present in a specific position within the key.

**Steps to Reproduce:**
1. Connect to Redis using client.connect().
2. Attempt to set a hash value using hSet:
```js
await client.hSet('user-session:123', {
      name: 'John',
      surname: 'Smith',
      company: 'Redis',
      age: 29
})
```

3. Observe the WRONGTYPE error.

**Workarounds:**
- Replacing hyphens with underscores (_); e.g., user_session:123 works as expected.
- Changing the position of the hyphen within the key can also resolve the issue.

Here is the whole code. Same code as the [documentation](https://redis.io/docs/connect/clients/nodejs/)
```js
const redis = require('redis');

async function redisImplementation() {
  const client = redis.createClient();

  client.on('error', err => console.log('Redis Client Error', err));
  
  await client.connect();
  
  await client.hSet('user-session:123', {
      name: 'John',
      surname: 'Smith',
      company: 'Redis',
      age: 29
  })
  
  let userSession = await client.hGetAll('user-session:123');
  console.log(JSON.stringify(userSession, null, 2));
}
```

**Environment:**
- **Node.js version:** 20.11.0
- **node-redis version:** 4.6.13
- **Redis server version:** 7.2.4
- **Operating system:** Intel i7 MacbookPro Sonoma 14.1

If it is possible i want to update the documentation.

**Comment by dwdougherty** [comment]
I tried the example on my machine and it works correctly. Just a thought: might you already have a key named 'user-session:123' that is a different type, say, a string? I get the same error if that's the case.

**Comment by Enes-Kayiklik** [comment]
> I tried the example on my machine and it works correctly. Just a thought: might you already have a key named 'user-session:123' that is a different type, say, a string? I get the same error if that's the case.

What stupid me :(, yes you are absloutly right. 

Actually this case came to my mind but when i try to call `hGet` it was throw an another error. Now i try to call `del` before `hSet` the issue fixed. 

Sorry for the useless issue.  Thanks for your patience!
