### ISSUE TITLE
Update sentinel documentation to include masters 

### ISSUE THREAD

**Issue by zulander1** [redis/redis-doc#2708]
When the client connects to sentinel, we are getting an error to include +sentinel|masters 

Url: https://redis.io/docs/management/sentinel/ under the section Sentinel Access Control List authentication 
'Lastly, for authenticating incoming client connections, you can create a Sentinel restricted user profile such as the following'

[This line](https://github.com/redis/redis-doc/blob/a8b76c9dcf0ea3c97d52dc9c8f1ec10fdc70de28/docs/management/sentinel.md?plain=1#L872) should be modified to :
`127.0.0.1:5000> ACL SETUSER sentinel-user ON >user-password -@all +auth +client|getname +client|id +client|setname +command +hello +ping +role +sentinel|get-master-addr-by-name +sentinel|master +sentinel|myid +sentinel|replicas +sentinel|sentinels +sentinel|masters `

**Comment by dwdougherty** [comment]
This is being fixed on the [new docs site](https://github.com/redis/docs) . Closing.
