### ISSUE TITLE
404 for /topics/persistence in Commands

### ISSUE THREAD

**Issue by joshrotenberg** [redis/redis-doc#2715]
The following Command pages have a broken link to `/topics/persistence`:

```
commands/bgsave.md
commands/bgrewriteaof.md
commands/save.md
commands/config-set.md
```

**Comment by dwdougherty** [comment]
Thank you for the report, Josh! Much appreciated. I'll get these changes in soon.

Please consider this repo as defunct; it will shortly be archived. You can open new issues [here](https://github.com/redis/docs) .

Closing.
