### ISSUE TITLE
Locating/Formatting SENTINEL commands 

### ISSUE THREAD

**Issue by therealbill** [redis/redis-doc#403]
I'm willing to write the docs on the SENTINEL commands, but want to make sure I have the correct place to put them.

I'll be adding some text to the topics/sentinel.md file to document the undocumented commands. I can also write the commands/sentinel.md file to document the command, but am unsure about where additional text should go. For example, SENTINEL is a command which only works if the server is invoked with sentinel mode. Does it need it's own section or just an entry in commands.json which looks like the rest? It is this latter question which is forefront of my mind on this at the moment.

**Comment by itamarhaber** [comment]
Hello @therealbill - If I am not mistaken, all Sentinal commands are documented at https://redis.io/topics/sentinel#sentinel-commands. I feel that adding these to the general commands would confuse most users, but that's just my opinion.

**Comment by therealbill** [comment]
Well, it is a five year old issue so I can’t really comment on it from then to today’s state. 😉 I’ll look later to the-familiarize myself with it.

**Comment by itamarhaber** [comment]
Time flies, eh? :) Thanks.

**Comment by nermiller** [comment]
Closing this issue as stale. Please reopen if needed.
