### ISSUE TITLE
Document SENTINEL sentinels <name> command

### ISSUE THREAD

**Issue by therealbill** [redis/redis-doc#404]
Moving this here from the command request on Redis' issue list. I'll be adding this in the next several days, but want to have it here to track it and refer to it in a pull request.

**Comment by antirez** [comment]
Hello Bill, I think the section about Sentinel removal is quite confusing, and does not really help to clarify what is going on. I would like to state things in a different way, just introducing the concepts of how Sentinel works (and what state is global, and what local, how slaves are managed) in a different way. I know the Sentinel doc sucks but this PR does not actually fix what we need to fix. However there are many typos that I would like to merge, so keeping this open. Thanks anyway for providing this changes.

**Comment by nermiller** [comment]
Closing as stale. Please reopen, if needed.
