### ISSUE TITLE
Use github API instead of hardcoded star values on `modules.json`

### ISSUE THREAD

**Issue by aviggiano** [redis/redis-doc#833]
The current [modules.json](https://github.com/antirez/redis-doc/blob/master/modules.json) file have hardcoded github stars, while it would be possible to get them through the [public API](https://developer.github.com/v3/#rate-limiting):

```bash
curl https://api.github.com/repos/aviggiano/redis-roaring | grep watchers_count
```

**Comment by itamarhaber** [comment]
ref #1030
