### ISSUE TITLE
redis-cli page is missing details about `.redisclirc`

### ISSUE THREAD

**Issue by itamarhaber** [redis/redis-doc#845]
See https://www.reddit.com/r/redis/comments/6mvluc/feature_request_environment_variables_for_rediscli/dk75j33/

**Comment by kingbuzzman** [comment]
What is even the point of this? hint/nohint -- why is this even a thing?

**Comment by mich-elle-luna** [comment]
.redisclirc is documented in https://redis.io/docs/connect/cli/, I'm not able to view the private reddit thread above, please re-open with details of the thread in the description if this is still needed.
