### ISSUE TITLE
key expiry and ttl during the evaluation of lua scripts

### ISSUE THREAD

**Issue by halaei** [redis/redis-doc#886]
As far as I know, these behaviors are not documented:

1. If a key with expiry (ttl) exists at the start of eval, it will not get expired during the evaluation of a script.
2. During the evaluation of a lua script, ttl of a key can go down to zero. After that, it remains zero until the script terminates.
3. To have logic based on the value of `ttl` can violate the concept of [scripts as pure functions](https://redis.io/commands/eval#scripts-as-pure-functions).

**Comment by halaei** [comment]
I think it would be better if `ttl` was constant during script evaluation.

**Comment by itamarhaber** [comment]
@halaei the points you've raised are good and, IMO, should be included in EVAL's documentation.

As for keeping ttls constant during script execution, I think that suggestion belongs in the https://github.com/antirez/redis repository. While I see your point in suggesting it, it would be a breaking change in terms of behavior, so I'd be hesitant about it.

**Comment by zuiderkwast** [comment]
Fixed in https://github.com/redis/redis/pull/10300. Time is now frozen during script exection. Regarding the points:

> 1. If a key with expiry (ttl) exists at the start of eval, it will not get expired during the evaluation of a script.

This is still true.

> 2. During the evaluation of a lua script, ttl of a key can go down to zero. After that, it remains zero until the script terminates.

Not true anymore. The TTL of a key doesn't change during script execution.

> 3. To have logic based on the value of ttl can violate the concept of [scripts as pure functions](https://redis.io/commands/eval#scripts-as-pure-functions).

Not true anymore.
