### ISSUE TITLE
[META] Undocumented core commands and subcommands

### ISSUE THREAD

**Issue by itamarhaber** [redis/redis-doc#974]
# Purpose

This meta-issue consolidates undocumented-related open issues and pull requests relating to core Redis commands and subcommands. The first comment (this one) will be updated periodically, feel free to discuss below.

# lt v5

## Undocumented core commands

* `ASKING` Cluster spec
* `GEORADIUS_RO` Geo readonly variant
* `GEORADIUSBYMEMBER_RO` Geo readonly variant
* `HOST:` HTTP vector borker
* `LATENCY` Issue: #821
* `MODULE` PR: #869 (needs review), #931
* `PFDEBUG` HLL debug function
* `PFSELFTEST` HLL test function
* `POST` - HTTP vector borker
* `PSYNC` - Partial sync
* `REPLCONF`
* `RESTORE-ASKING`
* `SUBSTR` - WTF?!? Where have you been all my life! (idendical to GETRANGE)

# Undocumented core subcommands

* `DEBUG SLEEP` Issue: #295 
* TBD more

# v5 and beyond

## Undocumented core commands

* `LOLWUT`

# Undocumented core subcommands

* `CLIENT LIST` PR: #942
* `CLIENT ID` PR: #972
* `CLIENT UNBLOCK` PR: #972

**Comment by IAmATeaPot418** [comment]
Adding two commands to this list:
1. hello
2. xsetid

**Comment by itamarhaber** [comment]
@IAmATeaPot418 actually,
`HELLO` (and `ACL` are only in the yet to be released v6, so not really undocumented yet)

**Comment by itamarhaber** [comment]
And `XSETID` iirc was ommitted intentionally as it is supposed to be an internal command.

Still, thanks for adding these, even if only for tracking's sake :)

**Comment by IAmATeaPot418** [comment]
Disregard then :) Thanks Itamar!

**Comment by mich-elle-luna** [comment]
Checked for documentation of all of these commands and all are documented except HOST and POST. Please re-open if those are still needed.
